### ISSUE TITLE
NMS.GEN.FLW.001 - FLW Data Import

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#101]
The NMS system shall provide means to upload FLW data into its internal database via a web interface via a CSV file (or web service).

Multiple upload attempts shall be supported whereby the complete FLW data may not be available in the beginning.

Errors during FLW data upload shall be logged.

**Comment by koshalt** [comment]
Is this still the plan of action with the data service from MOH coming up? If yes, I think we still have a gap in how the csv is authored or brought to the ops people...a can that we've been kicking down the road for a few months now

**Comment by llavoie** [comment]
Example of FLW data: 

https://gist.github.com/llavoie/fbe2106baed00746ec8e

**Comment by llavoie** [comment]
Fixed by @kamknitt
