### ISSUE TITLE
NMS.GEN.FLW.002 - FLW Identification

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#102]
NMS shall internally generate and maintain an FLW-ID for all FLWs that is called the NMS FLW-ID.
For external interfaces (including IVR and CSV upload), the FLW shall be identified first by the NMS FLW-ID if present.  Next the MCTS FLW-ID should identify them if it is provided.  If neither of those IDs is provided then the MSISDN should be used.

3.1.2.1.1	Additionally, for FLW records coming via CSV file, the record may optionally contain an FLW-ID provided by MoHFW called the MCTS FLW-ID 

MCTS FLW-ID is optional because data uploaded using training data may not have the FLW-ID issued by MCTS.

**Comment by llavoie** [comment]
Appendix A:

- FLW ID is a running number generated by MCTS which is unique within a state
- FLW ID in MCTS can be of 4 or 5 digits
- Combination of state ID and FLW ID is unique in MCTS across states

**Comment by llavoie** [comment]
In spite of what is described in the SRS, it appears that all of the APIs use only the callingNumber for identification of FLWs. So I believe that the FLW-ID and MCTS-FLW-ID are only interesting for reporting.

**Comment by larubbio** [comment]
I think those become useful when the MCTS upload of FLWs is played.
Basically MCTS can modify an FLW by specifying their MCTS-FLW-ID.  BBC can
modify an FLW via the other id or via calling number.

Through the API you are correct that it is only via calling number.

**Comment by llavoie** [comment]
Ok, great. All I'm doing with this ticket for now is adding those fields to FrontLineWorker. Nobody sets them yet.
