### ISSUE TITLE
NMS.GEN.FLW.003 - FLW Status

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#103]
The NMS system shall maintain the status of an FLW:
- **Anonymous**: Refers to any user who has called the MA/MK service and whose MSISDN number, FLW ID, name, and location data is not available in the FLW contact list maintained by the NMS system (in other words – only the MSISDN exists in the database). If an FLW record is uploaded for such a user, existing information (e.g. call records, language information) of the anonymous user shall not be deleted or over-written – however the FLW information not available in the NMS shall be added to the record (at which point they will become an 
Active FLW).
- **Active FLW**: Mandatory fields in the record of an FLW are present and following conditions are met:
  - FLW must have called NMS system once (via MA or MK)
  - FLW has a valid location  (State and District fields are mandatory and valid; other location fields if present are valid).
  - FLW has all the following parameters present in its record:
    - MSISDN number
    - Name
    - Designation
    - Mandatory parts of Location Data (NMS.GEN.LOC.002)
- **Inactive FLW**: A record of an FLW where all the mandatory fields have been filled in but the FLW has not called NMS system once (via MA or MK).
- **Invalid FLW**: Records of an FLW are partly/fully present but are not valid any more due to CSV upload procedure marking the FLW as invalid.

In case an FLW whose record does not exist in NMS calls via IVR and subsequently, the record of user is updated via file upload (from any source – MCTS or training data), In such case, the status of FLW record shall reflect the changes done via file upload.

**Comment by larubbio** [comment]
![screen shot 2015-04-27 at 10 16 42 am](https://cloud.githubusercontent.com/assets/51527/7353183/86c692a4-ecc6-11e4-951d-58872b06f74d.png)

**Comment by llavoie** [comment]
NMS.GEN.LOC.002 actually does not specify which location fields are mandatory. For now, the code will assume that Distriction and Language/Location Code are sufficient.

@pankajnagpal30 it would be great to get clarification on this.

**Comment by llavoie** [comment]
Also, @pankajnagpal30, what is an FLW Designation? I don't see the values for this field defined in any spec. Thanks!

**Comment by larubbio** [comment]
![](http://www.menwithfoilhats.com/wp-content/uploads/2011/02/stickdrawing.jpg)
