### ISSUE TITLE
NMS.GEN.FLW.004 - FLW Validation checks on upload

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#104]
The NMS system shall perform the following checks and validation before uploading FLW data into the FLW database:
- If an FLW’s record in NMS already has an NMS or MCTS FLW ID, and new data about this FLW is uploaded in CSV format, then this new data will be considered an Update (see other requirements in this section).
- FLW has valid location data (i.e., refer #103 NMS.GEN.FLW.003).
- The data shall be validated based on the specified format for each field (i.e. string data, number etc.)  and Presence (Mandatory/Optional) as specified in Appendix A.

**Comment by larubbio** [comment]
As part of this ticket I think we will have to extend the location tracking for an FLW.  Reporting needs to display usage of MA/MK down to the village and health center level.  Currently we only track FLW location to the district.

I think we will need to store the lowest level of location we receive in the csv upload in the FLW record.  I think we should reject a record if the location of district or lower is not provided.  We should then save only the lowest level and provide a bean validator that verifies only the lowest level is set.

**Comment by llavoie** [comment]
We're going to need the same logic for Kilkari beneficiaries so it would be great if this could live somewhere common.

**Comment by llavoie** [comment]
@frankhuster @koshalt  Is one of you working on the common "location validation" API or is that already in?

**Comment by frankhuster** [comment]
Haven't worked on it yet.

**Comment by koshalt** [comment]
On me. Will be in tomorrow.

**Comment by larubbio** [comment]
There is no NMS FLW Id in the mcts import file so an existing flw will be searched by mcts id/state or msisdn
