### ISSUE TITLE
NMS.GEN.FLW.005 - Modification of FLW phone number via CSV upload

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#105]
The NMS system shall allow modification of MSISDN of an existing FLW record using CSV upload by providing new MSISDN number in a record with an existing NMS FLW-ID or MCTS FLW ID. Or via MDS UI by locating the record in the UI. 
- If a new MSISDN is uploaded for the same FLW ID (already existing in NMS), say FLW-A, then the old MSISDN will be replaced with the new MSISDN. 
- If the MSISDN number already exists for a different FLW (with a different NMS or MCTS FLW ID) in NMS the request shall be rejected. 

NMS shall allow only one FLW to have any given MSISDN number. 

Change of MSISDN number is not recommended for an FLW but none-the-less very likely to happen in states where government SIMs have not been distributed.

In order to realize use-case of reusing an existing MSISDN number, either the MSISDN number of FLW-B has to be changed, or FLW-B has to be marked invalid.

**Comment by llavoie** [comment]
Aricent had originally been pushing for BBC to do this via the UI. This probably makes the most sense.

**Comment by larubbio** [comment]
I think this is the format used in the existing system.  The NMS format will either be the same, or very similar.  Note that the msisdn is more than 10 digits so it will need to be converted to take the last 10 digits.

![image](https://cloud.githubusercontent.com/assets/51527/7894621/e1e17630-0621-11e5-93cf-4b4c353c8521.png)

**Comment by larubbio** [comment]
The file that we are using includes mcts flw id but no state. That id is only unique within a state.
