### ISSUE TITLE
NMS.GEN.FLW.007 - Notify user of rejected/ignored uploaded FLW records

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#107]
NMS shall note and make available to the user all rejected/ignored uploaded FLW records

**Comment by koshalt** [comment]
For this ticket, we currently throw a csv exception and unroll the transaction. Should we consider creating an flw error entity to store the exceptions or just rely on logging to 'inform the user' ?

**Comment by larubbio** [comment]
Are we ignoring any records?  If not I would close the ticket since we log the error and the line number (and maybe return that in the http response)

**Comment by koshalt** [comment]
Not ignoring any record. Safe to close.
