### ISSUE TITLE
NMS.GEN.FLW.008 - Ability to mark FLW invalid via UI or CSV upload

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#108]
The NMS system shall provide means to mark an FLW as invalid using CSV upload or MDS UI. 
Once an FLW is marked invalid, any incoming call with MSISDN that is same as that of invalid FLW shall be treated as that of an anonymous caller.

**Comment by srivastavaAbhi** [comment]
There is no such field in FLW Csv provided by MCTS which says that flw is inactive.

**Comment by larubbio** [comment]
This CSV would come from BBC, not MCTS.  I think they shared the format with us, but I'm not sure.

cc @llavoie

**Comment by llavoie** [comment]
I don't think I've seen a sample file (we do have some sample CSVs from
BBC, but not for updating FLW status). But as we discussed yesterday, the
columns should probably be MSISDN, the various IDs supported for FLWs, and
the updated Status.

On Fri, Jun 5, 2015 at 9:54 AM, Rob LaRubbio <notifications@github.com>
wrote:

> This CSV would come from BBC, not MCTS. I think they shared the format
> with us, but I'm not sure.
>
> cc @llavoie <https://github.com/llavoie>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/108#issuecomment-109361664>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by larubbio** [comment]
I haven't seen those files either.  For #124 I'm using these headers for the FLW IDs.

"NMS FLW-ID,MCTS FLW-ID,MSISDN,LANGUAGE CODE"

We should be consistent across these csv's if we can.

**Comment by larubbio** [comment]
@llavoie If all updates are coming from mcts then how will we handle this case?

**Comment by larubbio** [comment]
This can be one via the UI according to the monday night call.
