### ISSUE TITLE
NMS.GEN.MCTS.003 - Validation checks during beneficiary upload

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#111]
The NMS system shall perform the following checks and validation during upload of MCTS file along with NMS.KK.ACCESS.006 and NMS.GEN.DEPL.004:
- MCTS data shall have valid location information (State and District fields are mandatory and valid; other location fields if present are valid).
- MCTS data does not have an MSISDN that is already being used by another active MCTS beneficiary for same pack.
- If a beneficiary’s record in NMS already has an MCTS-Id present, and new data from MCTS is uploaded with the same MCTS ID, then it shall be considered as case of information update (see other requirements in this section).
- At-least one out of LMP or DOB must be present in each record that is uploaded from MCTS.
- The data shall be validated based on the specified format for each field (i.e. string data, number etc.)  and Presence (Mandatory/Optional) as specified in Appendix A.

**Comment by larubbio** [comment]
@llavoie Should this issue be closed now?

**Comment by llavoie** [comment]
Yes.
