### ISSUE TITLE
NMS.GEN.MCTS.006 - Ability to modify kilkari beneficiary address via UI or CSV

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#114]
The NMS system shall provide means to modify the address/location of a Kilkari Beneficiary by providing new address/location information along with existing MCTS ID using CSV upload or MDS UI.

A history/change table shall be created with old and new address/location for the existing beneficiary.
The language mapping for the beneficiary does not change due to change in location information.

**Comment by larubbio** [comment]
@llavoie @pankajnagpal30 Is there a file for this upload?

**Comment by llavoie** [comment]
I have it and I'm working on this. Sorry I forgot to assign it to myself.
I'm going to make sure all of the Kilkari beneficiary tickets are assigned
to me right now...

On Wed, Jun 24, 2015 at 2:48 PM, Rob LaRubbio <notifications@github.com>
wrote:

> @llavoie <https://github.com/llavoie> @pankajnagpal30
> <https://github.com/pankajnagpal30> Is there a file for this upload?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/114#issuecomment-115021436>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*
