### ISSUE TITLE
NMS.GEN.MCTS.008 - Ability to modify kilkari beneficiary mother/child status via UI or CSV

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#116]
The NMS system shall provide means to update mother/child status of a Kilkari Beneficiary using CSV upload or MDS UI. The following information status fields shall be available in internal database of NMS:
- Miscarriage/Abortion
- Still birth
- Child death
- Maternal Death

**Comment by llavoie** [comment]
Blocked on spec clarification. I sent the following email:

Hi Pankaj,

Requirement NMS.KK.ACCESS.010 in the SRS says that we should auto-deactivate Kilkari subscriptions when MCTS data indicates Miscarriage/Abortion, Child Death, Maternal Death, or Stillbirth. Do you know which MCTS fields would give us this information? I do see a column for Abortion (although the only values I see in it are blank and None, so I'm not sure how "yes" gets indicated), but not for the other events.

This is the sample data I have for mothers:
https://gist.github.com/llavoie/5bed1a3c3615690b79e4

Thanks,
L

**Comment by llavoie** [comment]
Response from Pankaj:

·         Miscarriage / Abortion: The field is available with the name as Abortion and the possible values of abortion field are

o   MTP<12 Weeks

o   Spontaneous

o   MTP>12 Weeks and

o   None

·         Death (Maternal /Child): The status will be available in the Entry_Type and the integer values in this field could be

o   1 - Active

o   2 - Migrated In

o   3 - Migrated Out

o   9 – Death.

·         Still Birth: The data for still birth will be available in outcome_nos and in case it is stillbirth the value will be updated to 0. In case there are children, it will change into other numerical value like 1 or 2 and the name of children will also come.

**Comment by larubbio** [comment]
@llavoie Is the referenced file the one that will be uploaded for this?  Is that file also being used for other upload stories?  Just wondering if I can take this ticket in isolation or if it should be done with other tickets.

**Comment by llavoie** [comment]
It's probably easiest if I do this because I'm refactoring the import/update code right now. I learned from Pankaj that status updates will always come from MCTS, and there are 3 different fields we need to look at.
