### ISSUE TITLE
NMS.GEN.MCTS.010 - MSISDN storage format

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#118]
NMS shall store MSISDN number in 10-digit format in its internal database for an FLW/ beneficiary. 
On any interface if the MSISDN number has 10 digits or 11 digits or 12 digits, then during storage and retrieval, the appropriate conversion shall be done by NMS.

**Comment by llavoie** [comment]
We'll handle this by only ever storing 10-digit phone numbers (and converting at import time if needed).

**Comment by larubbio** [comment]
Waiting on a fix from @frankhuster for CdrFileServiceBundleIT.testValidRequest
