### ISSUE TITLE
NMS.GEN.LANG.005 - Use existing languageLocationCode

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#123]
Once the “Language-location code” of an FLW/MCTS-beneficiary is determined by any of the requirements listed above, the same “Language-location code” shall be used in future and the language determination process shall not be repeated.

This also applies to the case across MA and MK service i.e. “Language-location code” determined for a MSISDN number during MA service shall be applicable to MK service and vice versa.

**Comment by llavoie** [comment]
This might be done -- please validate.

**Comment by larubbio** [comment]
When creating a subscription in kilkari if the user does not have their language set we need to use the language that is sent.

When loading the user in kk get user we need to set the language
