### ISSUE TITLE
NMS.GEN.CFG.001 - System configuration

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#125]
The NMS system shall have means to provide configuration parameters to various services. 
The configuration parameters shall be classified into following:
- **System Parameters** (e.g. IP address, DB location, FTP/SFTP parameters) that are handled by property/config files.
- **Business Logic parameters** related to NMS service (e.g. Capping rules, Language settings, etc.) that are handled by UI interface.

For key configuration parameters, refer section Configuration Parameters. 

The UI interface shall be realized using the existing MDS UI interface offered by MOTECH platform.  
(The SRS says it will be the MDS UI.  It doesn't have to be the MDS UI, it just has to be a UI)

**Comment by llavoie** [comment]
These are the configuration parameters mentioned in the spec (section 7.4):

MA:
Capping information (refer NMS.MA.ACCESS.003,
NMS.MA.ACCESS.004)
Configurable # of days of retry for course SMS delivery

MK:
Capping information (refer NMS.MK.ACCESS.003,
NMS.MK.ACCESS.004)

KK:
# of Messages/week (NMS.KK.OBD.001)
Maximum # of active KK subscriptions allowed as per current
deployed system including HW

Nation
Default location for anonymous users (for MA service)
Default language used by a service in whole nation

State Specific Parameters:
Language Mapping to group of districts of a state (location-
language code)
List of cards used in MK service per state
State specific content files
State-circle-district-Location_language mapping

Circle
Default language used by a service for any circle (used especially
when there are multiple states per circle)

Reports:
FTP information for saving reports on FTP server

System:
Log Levels

**Comment by larubbio** [comment]
There are other params like max allowed end of usage prompt that is
currently hardcoded in UserController.  I think the get user api has a
couple others that should be pulled out.
