### ISSUE TITLE
NMS.MA.CFG.004 - Store config in a version controlled file

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#128]
(The requirement id for this is incorrect in the SRS.  It is NMS.MA.CFG.004 but should be NMS.GEN.CFG.004)

The NMS system level configuration parameters shall be stored in a version controlled file.  
Changes to any configuration parameter shall be first done in version management system and subsequently taken to use.

Hard coded default shall be avoided.

**Comment by llavoie** [comment]
Operation requirement, closing.
