### ISSUE TITLE
NMS.GEN.SECU.004 - Don't log personal information

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#129]
The NMS system shall not log any personal information that can identify a user.

There may not be an automated way to detect or prevent this.  Instead disk encryption for the log files may be used and the log files will be purged on a regular pre-defined schedule (e.g. using logrotated).

**Comment by llavoie** [comment]
Putting in sprint 3 for us to review and ensure we haven't logged any personal info.

**Comment by llavoie** [comment]
Does this only apply to log files, or should it also include "error log" tables that we might create for requirements like #117  and #107?

**Comment by larubbio** [comment]
I think just files.  The database will have PII in it already so adding
more in a logging table isn't an issue.
