### ISSUE TITLE
NMS.GEN.DEPL.004 - Maintain deployment status of services for each state

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#134]
The NMS system shall maintain deployment status for each service (Deployed/Not-deployed) for each state. 

If any incoming request is received for a service from a state that is Not-deployed in that state, then appropriate error message shall be played (e.g. Service Not Available in the state) in standard Hindi.
Deployment state of service shall not influence the data upload procedures mentioned in Data & Language Management section for MA, MK and KK (i.e. FLW and beneficiary data upload for a given state shall be allowed even if the service is not deployed in the state).

**Comment by llavoie** [comment]
New entity DeployedService with fields:

Service
State

If no entry in table, assume not deployed
Check this table from all getUser APIs and when user's language gets set 

Could live in region module (or potentially a new module, but region might make more sense)

**Comment by larubbio** [comment]
I started work on this, but I wasn't able to finish it before I had to head out.  You can pick it up from my branch (https://github.com/motech-implementations/mim/tree/%23134) or start over.

While working on it I noticed a couple of things:

 - The API tests are out of control, specifically in regards to data creation.
 - The API layer for get user and maybe set language needs to be refactored.  The rules are a little complex and the order items are loaded can vary based on what needs to be checked.  For example we do a couple of state based checks (whitelist and service deployment).  We can get an FLWs state three ways (they can have it associated with them if they come from MCTS, The circle they are calling from may be associated with a single state or the language location code associated with them.)
 - There was a third but I forget it.
