### ISSUE TITLE
NMS.GEN.LOG.005 - FLW and Kilkari beneficiary history tracking

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#137]
NMS system shall maintain a history of all changes made to FLW and MCTS-beneficiary records via code.  Tracking of changes via UI is tracked under #475

**Comment by llavoie** [comment]
turn on auditing

**Comment by larubbio** [comment]
Instead of turning on auditing I was thinking of creating a history tracking service.  When a field is changed via a setter the history tracking service can be called to record the old and new value.  We can then use the @InstanceLifecycleListener(InstanceLifecycleListenerType.PRE_UPDATE) to flush the history tracking object.

**Comment by larubbio** [comment]
@llavoie What object would you consider the MCTS beneficiary?  The Subscriber, MctsBeneficiary, MctsMother or MctsChild?

**Comment by llavoie** [comment]
MctsMother and MctsChild would both be considered beneficiaries (both
extend MctsBeneficiary).

On Wed, Jun 24, 2015 at 3:41 PM, Rob LaRubbio <notifications@github.com>
wrote:

> @llavoie <https://github.com/llavoie> What object would you consider the
> MCTS beneficiary? The Subscriber, MctsBeneficiary, MctsMother or MctsChild?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/137#issuecomment-115034491>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by larubbio** [comment]
If i have a history tracking table, could I just relate
to nms_mcts_beneficiaries or would I need to relate to the other tables?

**Comment by llavoie** [comment]
I'm not sure -- we'd need to test it out.

On Wed, Jun 24, 2015 at 3:43 PM, Rob LaRubbio <notifications@github.com>
wrote:

> If i have a history tracking table, could I just relate
> to nms_mcts_beneficiaries or would I need to relate to the other tables?
>
> On Wed, Jun 24, 2015 at 3:42 PM, Lauren Lavoie <notifications@github.com>
> wrote:
>
> > MctsMother and MctsChild would both be considered beneficiaries (both
> > extend MctsBeneficiary).
> >
> > On Wed, Jun 24, 2015 at 3:41 PM, Rob LaRubbio <notifications@github.com>
> > wrote:
> >
> > > @llavoie <https://github.com/llavoie> What object would you consider
> the
> > > MCTS beneficiary? The Subscriber, MctsBeneficiary, MctsMother or
> > MctsChild?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/motech-implementations/mim/issues/137#issuecomment-115034491
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Lauren Lavoie
> > Software Development Manager, Mobile Health Innovations
> > Grameen Foundation
> > 2101 4th Ave | Suite 1550 | Seattle, WA 98121
> > 206-325-6690 ext 254
> > llavoie@grameenfoundation.org | Skype:laurenlavoie
> > Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
> > <http://twitter.com/grameenfdn>│YouTube
> > <http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
> > *Connecting the World's Poor to Their Potential*
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/motech-implementations/mim/issues/137#issuecomment-115034699
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/137#issuecomment-115034868>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by larubbio** [comment]
Ok.  If anyone gets to this before me I was thinking we could create an object like the following:

```java
@Entity
public class AuditLog extends MdsEntity {
    @Field
    private FLW flw;

    @Field
    private MctsMother mother;

    @Field
    private MctsChild child;

    @Field
    private enum changeType;

    @Field
    private String change;

   // If we have a user we should store it as well unless MDS does that for us. 
}
````

Then in each object when a setter is called we'll load or a create a singleton instance of the AuditLog object for that particular entity instance.  The setter will then notify it of the field name being changed, the old and new value.  The AuditLog object will keep a record of all modifications and then using the instance lifecycle listener convert the changes to a string and save one line in the audit log when the tracked object is saved, created or deleted.

**Comment by larubbio** [comment]
This mechanism should also be used for #142

**Comment by larubbio** [comment]
Thinking about this a little more, I wonder if instead we want to create either a common base class, or an @TrackChanges annotation that can be placed on setter methods (or on a class that would reflectively detect all setters).  Then when a setter is called it could store the original value and the new value.

**Comment by llavoie** [comment]
That sounds like a nice approach to me.

On Thu, Jun 25, 2015 at 8:20 AM, Rob LaRubbio <notifications@github.com>
wrote:

> Thinking about this a little more, I wonder if instead we want to create
> either a common base class, or an @TrackChanges annotation that can be
> placed on setter methods (or on a class that would reflectively detect all
> setters). Then when a setter is called it could store the original value
> and the new value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/137#issuecomment-115290266>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by frankhuster** [comment]
That's an elegant solution.
I like.

On Thu, Jun 25, 2015 at 8:20 AM, Rob LaRubbio <notifications@github.com>
wrote:

> Thinking about this a little more, I wonder if instead we want to create
> either a common base class, or an @TrackChanges annotation that can be
> placed on setter methods (or on a class that would reflectively detect all
> setters). Then when a setter is called it could store the original value
> and the new value.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/137#issuecomment-115290266>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by kamknitt** [comment]
As I understand, we want to inject some logic to entity setters. I'm trying to use AOP for this, but things are a bit complicated because our entities are not managed by Spring. The solution for this is to mark entities we want to track with @Configurable annotation and allow load-time class weaving, but I'm having classloading issues with this. I'm afraid it might be a pain to get it to work. Do you have any suggestions of other approaches?
I also have a question about storing audit logs. I understand that we want to use the HistoryTrackingService to map tracked instances with changes (in the form of Map<Object, AuditLog>). Then on PRE_STORE event the audit log is persisted and removed from HistoryTranckingService mapping. But what if PRE_STORE will never happen for the instance (e.g. we called the setter on the instance without the persistence context)? Will we have to clean the mapping manually? Other approach is to restrict AuditLog creation to situations in which the tracked instance has a persistence context. Am I missing something here?
Last question about what exactly the AuditLog represents. Do we want to store all instance changes within one transaction in a single AuditLog like this: "language(HIN, ORI), status(ACTIVE, INACTIVE)" or in separate AuditLog for each changed field, like: "language(HIN, ORI)" and "status(ACTIVE, INACTIVE)"?

**Comment by frankhuster** [comment]
I'm pretty sure the answer the last question is: you want to store all
entity changes in just one line.

On Fri, Jun 26, 2015 at 7:14 AM, kamknitt <notifications@github.com> wrote:

> As I understand, we want to inject some logic to entity setters. I'm
> trying to use AOP for this, but things are a bit complicated because our
> entities are not managed by Spring. The solution for this is to mark
> entities we want to track with @Configurable annotation and allow load-time
> class weaving, but I'm having classloading issues with this. I'm afraid it
> might be a pain to get it to work. Do you have any suggestions of other
> approaches?
> I also have a question about storing audit logs. I understand that we want
> to use the HistoryTrackingService to map tracked instances with changes (in
> the form of Map). Then on PRE_STORE event the audit log is persisted and
> removed from HistoryTranckingService mapping. But what if PRE_STORE will
> never happen for the instance (e.g. we called the setter on the instance
> without the persistence context)? Will we have to clean the mapping
> manually? Other approach is to restrict AuditLog creation to situations in
> which the tracked instance has a persistence context. Am I missing
> something here?
> Last question about what exactly the AuditLog represents. Do we want to
> store all instance changes within one transaction in a single AuditLog like
> this: "language(HIN, ORI), status(ACTIVE, INACTIVE)" or in separate
> AuditLog for each changed field, like: "language(HIN, ORI)" and
> "status(ACTIVE, INACTIVE)"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/137#issuecomment-115703083>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by larubbio** [comment]
I'm not sure I have any other solutions.  I was thinking AOP would be
best.  If not would an annotation on each setter help at all?  If not then
this might have to be done the old fashioned way with a method call in each
setter.

I wasn't thinking we would use the history tracking service for this.  I
was thinking we would have a different object that simply kept track of the
changes (maybe a map with the key being the field name and the value being
a two element array (old, new))  Then during the pre_store event that map
would get converted to the single audit line that was stored in the
database.

I'm not sure I follow the part about persistence context.

For the last part, Frank is correct.  One entry with all changes on a
single line.

-Rob

**Comment by llavoie** [comment]
Hi @kamknitt -- any luck with the AOP approach or using an annotation on each setter?

**Comment by kamknitt** [comment]
I've managed to get it to work. Unfortunatelly, there are some limitations. The most important is that each modification (setter invocation) must take place in a transaction and must be done to the instance that is attached to the PM. This makes it impossible to track updates done by MDS UI (adding @Transactional around some methods in Motech would make it possible, but there might be some issues with that; it needs to be tested).
I've pushed current changes to a branch: https://github.com/motech-implementations/mim/tree/137. For now it contains only FLW part. I think I should finish it by tomorrow.
I've also had to do some changes to Motech: http://review.motechproject.org/#/c/5398/.

**Comment by llavoie** [comment]
Thanks for the update on this Kamil!

On Wed, Jul 8, 2015 at 9:11 AM, kamknitt <notifications@github.com> wrote:

> I've managed to get it to work. Unfortunatelly, there are some
> limitations. The most important is that each modification (setter
> invocation) must take place in a transaction and must be done to the
> instance that is attached to the PM. This makes it impossible to track
> updates done by MDS UI (adding @Transactional
> <https://github.com/Transactional> around some methods in Motech would
> make it possible, but there might be some issues with that; it needs to be
> tested).
> I've pushed current changes to a branch:
> https://github.com/motech-implementations/mim/tree/137. For now it
> contains only FLW part. I think I should finish it by tomorrow.
> I've also had to do some changes to Motech:
> http://review.motechproject.org/#/c/5398/.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/137#issuecomment-119641936>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by larubbio** [comment]
@kamknitt I think this is closed, if not please reopen.
