### ISSUE TITLE
NMS.GEN.LOG.009 - IVR Interaction logging

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#141]
NMS system shall log all interactions with IVR including but not limited to the following:
- Incoming Call 
- Outgoing Call 
- Outgoing SMS 
- Bookmark information
- Other Message Exchanges

**Comment by llavoie** [comment]
Need to think about how we do this without logging PII.

**Comment by frankhuster** [comment]
I'm assuming that LOGGER.info("xxx") is what's needed and will proceed to verify all locations in the code that interact with IMI have such a LOGER.info statement.
Good enough?

**Comment by frankhuster** [comment]
And will make sure to hide phone numbers, which are the only PII we have, right?

**Comment by llavoie** [comment]
Actually I think what's intended by this ticket is logging the interactions in the DB. @larubbio?

-----Original Message-----

**Comment by larubbio** [comment]
I do think it is meant to log to the DB but that doesn't have to be the case.  We could also log one line per-interaction to an ivr.log file.  The trouble with that is that there is no plan for pulling and aggregating log files.

I assume we'll have a table that tracks API calls from/to the IVR.  So we should intercept each of the calls in the API layer and log the call id if we have it, the api that was called, maybe the api start and end time as well as the ultimate result.  This will be tricky with exceptions, so we may need to create a call specific state object that we can log at the end of each api method or in the exception handler.

For calls we make to the IVR I think the logging will be easier.  

I think this was meant to help the operations team, so we may want to check with them to see if they will use it.

**Comment by frankhuster** [comment]
> so we may want to check with them to see if they will use it.
Should I wait on this ticket until we hear from the ops team?
How do we ask the ops team?
Feeling useless...

**Comment by llavoie** [comment]
We could try asking Abhishek who would be the appropriate person to ask at
Aricent?

On Thu, Jun 4, 2015 at 10:10 AM, Frank Huster <notifications@github.com>
wrote:

> so we may want to check with them to see if they will use it.
> Should I wait on this ticket until we hear from the ops team?
> How do we ask the ops team?
> Feeling useless...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/141#issuecomment-108978355>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by frankhuster** [comment]
Cool, can someone who is physically in the office ask him?

On Thu, Jun 4, 2015 at 10:28 AM, Lauren Lavoie <notifications@github.com>
wrote:

> We could try asking Abhishek who would be the appropriate person to ask at
> Aricent?
>
> On Thu, Jun 4, 2015 at 10:10 AM, Frank Huster <notifications@github.com>
> wrote:
>
> > so we may want to check with them to see if they will use it.
> > Should I wait on this ticket until we hear from the ops team?
> > How do we ask the ops team?
> > Feeling useless...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/motech-implementations/mim/issues/141#issuecomment-108978355
> >
> > .
> >
>
>
>
> --
> Lauren Lavoie
> Software Development Manager, Mobile Health Innovations
> Grameen Foundation
> 2101 4th Ave | Suite 1550 | Seattle, WA 98121
> 206-325-6690 ext 254
> llavoie@grameenfoundation.org | Skype:laurenlavoie
> Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
> <http://twitter.com/grameenfdn>│YouTube
> <http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
> *Connecting the World's Poor to Their Potential*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/141#issuecomment-108982878>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by llavoie** [comment]
Abhishek wasn't sure whether anyone would need it (although it would likely be the L3 support folks if anyone -- which will be GF + Aricent jointly for the first few months). He thought we should route the question through Pankaj.

**Comment by frankhuster** [comment]
OK, do we have a "waiting for Pankaj" label?

On Thu, Jun 4, 2015 at 10:38 AM, Lauren Lavoie <notifications@github.com>
wrote:

> Abhishek wasn't sure whether anyone would need it (although it would
> likely be the L3 support folks if anyone -- which will be GF + Aricent
> jointly for the first few months). He thought we should route the question
> through Pankaj.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/141#issuecomment-108986570>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by frankhuster** [comment]
So after discussing with everybody (including @pankajnagpal30) in the office, we decided to use debug logging with care to remove all PII
