### ISSUE TITLE
NMS.GEN.LOG.010 - Audit trail logging

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#142]
NMS system shall have audit trail logs that includes but not limited to the following:
- Any NMS CSV upload 

The audit trail log shall include event details, date/time of event and user credential information among others.

**Comment by frankhuster** [comment]
Does "Audit trail log" mean an entry in a database table or a line in the tomcat log file or something else?

**Comment by koshalt** [comment]
Pretty sure this is db. Tomcat logs are usually ephemeral (and for debugging)

On a side note, we were originally going to rely on history tracking to get this done, from what I remember.

**Comment by larubbio** [comment]
We were going to rely on history tracking, but I'm concerned about how much data it might end up saving.

For the CSV uploads I think we need a seperate audit table, hopefully we can add that in one place in the csv module.

For changes through the UI that might be difficult since the only way we can hook into it would be with a trigger or the history tracking.

For changes to business logic I think we can turn on history tracking (actually maybe not.  my concern with history tracking is that all related objects also have to have history tracking turned on.  Then for each change the entire graph of objects are copied)  So tracking history for config objects is fine, but for things with relationships to domain tables it might get messy
