### ISSUE TITLE
NMS.MA.COURSE.002 - Course completion criteria

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#149]
An MA course shall be considered to have successfully finished if:
- The FLW has finished listening to all the lessons of all the chapters.
- The FLW has taken all the quizzes of all the chapters.
- The FLW has attained at least 50% marks in the quiz (22 or greater marks out of 44).

Once course is completed, the call shall be disconnected and the bookmarks are reset. When the user dials next time, the user is automatically taken to welcome message.

**Comment by koshalt** [comment]
Questions for @pankajnagpal30 and BBC -

1. There is no workflow from a completed course state to restarting the course again. This means that the next time an FLW calls in, they start out like a new user (as opposed to playing an ivr message saying we noticed you finished the course, do you want to restart, etc)

2. Pass Citeria
This is always the total score right? If the user got a 0 in 5 of the chapters but scored great in the rest to make up for the 22 needed to pass, they are still considered passing?

2. What should we do if a user completes a course but fails the pass criteria of > 50% score? 
- Do they get an option to restart the course? 
- Do we not reset their bookmarks?
- Who makes this decision? (IVR vs motech)

**Comment by koshalt** [comment]
@llavoie @larubbio This is implemented as we understand the feature today with followup questions to BBC. Should be mark the issue as  -

* closed and open a separate tracking for the possible followup changes?
OR
* move to sprint 3?
OR
* leave it open here?

**Comment by llavoie** [comment]
I like option (1) -- and put the new ticket in sprint 3 as we likely won't get clarity in time for sprint 2.

**Comment by koshalt** [comment]
ok, #245 created for Sprint 3 to followup. Closing this issue.
