### ISSUE TITLE
api/obd - Call Notification

### ISSUE THREAD

**Issue by llavoie** [motech-implementations/mim#15]
4.2.8 Call Notification API
This API is called by IVR Platform in following conditions are met:
1. Call Notification URL is defined for the service
2. Final-status of the OBD Request is updated as either Success, Failed or Rejected.

**Comment by llavoie** [comment]
@pankajnagpal30 is this API (defined in section 4.2.8 of the API spec) obsolete now that we are doing all CDR processing in batch based on the CDR file? Oddly, I don't see this API at all in the OBD sequence diagram in section 4.1.5.

**Comment by larubbio** [comment]
I don't think we need this.  We should make sure we do not provide a Call Notification URL in the target file.
