### ISSUE TITLE
NMS.MA.COURSE.003 - SMS on successful course completion

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#150]
If FLW completes MA course successfully (either first time or during re-attempt) then MA service shall send an SMS to the FLW with a reference number. 

The SMS sent to user shall be in native language in Roman Characters.

The NMS system shall track delivery notification of the SMS and continue retry of SMS once every day till successful delivery for configurable number days.

The reference number is concatenation of MSISDN, Location Id and Course-Repeat attempt.

An FLW currently takes the SMS to their ASHA Divas meeting at the Block Level, where the certificates are handed out. MoHFW may devise a different process for handing out certificates in the future.

The certificates are given to FLWs who are identified as being genuine by the local health authority.  It is outside the scope of this document if certificates are re-issued if the FLW successfully completes the course and gets a certificate but for some reason decides to do the course again. From SW point of view, the handling of first successful attempt and re-attempt shall be same.

Location Id is a unique identifier for a particular record of location data.  For an anonymous user, location Id is set to default value (refer section Configuration Parameters).

**Comment by koshalt** [comment]
This is completed and checked in. The open questions from this ticket (sms content) is currently tracked with #284
