### ISSUE TITLE
NMS.KK.ACCESS.002 - Kilkari activation via IVR

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#156]
Kilkari Services for a beneficiary can be subscribed via IVR Long code. There shall be separate long codes for Each pack.

Service shall be “activated” from the date of IVR call (subscription state = Active).

Exact long code shall be finalized during deployment. 

Subscription via IVR would imply that the location and other vital information of the beneficiary shall not be available in the NMS (only MSISDN and LMP/DOB shall be determined based on date of call) such that subscription for various packs start from next day.

IVR system shall identify the circle that the user is calling from (from their mobile number) in order to identify their language preference. If there are multiple languages available in the circle (North East for example) the user will be prompted to enter a language code, obtained from their ASHA, to set the language. The default prompt will be in the default language for their circle, or Hindi if circle is not known. Refer section 3.1.4 for details on language selection.

**Comment by larubbio** [comment]
![screen shot 2015-04-27 at 10 27 30 am](https://cloud.githubusercontent.com/assets/51527/7354054/4c1b732a-eccd-11e4-8250-7e8b5480f1e7.png)

**Comment by llavoie** [comment]
This needs clarification -- are subscribers supposed to be activate or pendingActivation when created?
