### ISSUE TITLE
NMS.KK.ACCESS.006 - Reason to reject a subscription (more multiple MSISDN subscription rules)

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#159]
Kilkari Service shall not allow multiple “Active” or “Pending Activation” subscriptions for the same pack on the same MSISDN via bulk upload of MCTS Data or via IVR. In particular, subscription request with a particular MSISDN, shall be rejected IF: 
- DOB (with or without LMP) is present in the MCTS record and there is an already “Active” subscription to Child Pack on this MSISDN
- LMP (without DOB) is present in the MCTS record and there is an already “Active” or “Pending Activation” subscription to Pregnancy Pack on this MSISDN.
- IVR Subscription is requested and there is an already “Active” or “Pending Activation” subscription to that Pack on this MSISDN.
If Subscription for a pack is completed or gets deactivated, then only new subscription for the 

In case of MCTS bulk upload, rejected record should be logged.

In case of IVR, the subscription failure message should be played to the user.

**Comment by llavoie** [comment]
This ticket (and presumably others) requires us to log information (in this case a rejected subscription request). Has anyone else already dealt with this for another ticket, and if so, where are you logging to?
@larubbio @koshalt @frankhuster

**Comment by larubbio** [comment]
I think the logging on this ticket refers to logging the MCTS upload
results.  There are other tickets that have similar logging reqs. (I think
all of the upload stories).  I assume we'd log to a DB table and have a
view similar to the SMS log.  Another module? :)

**Comment by frankhuster** [comment]
A Logging module sounds fun!

On Tue, Apr 28, 2015 at 8:24 PM, Rob LaRubbio <notifications@github.com>
wrote:

> I think the logging on this ticket refers to logging the MCTS upload
> results. There are other tickets that have similar logging reqs. (I think
> all of the upload stories). I assume we'd log to a DB table and have a
> view similar to the SMS log. Another module? :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/159#issuecomment-97293154>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201
