### ISSUE TITLE
api/kilkari - Get Subscriber Details

### ISSUE THREAD

**Issue by llavoie** [motech-implementations/mim#16]

**Comment by frankhuster** [comment]
Starting over from the erroneously located comments in #9 which actually belong here.

It looks like we need to return an empty subscriptionPackList for new/inexistant users.
But then I wonder what the two sample returns from the API spec mean:
```json
{
   "circle": "AP",
   "defaultLanguageLocationCode": "10"
}
```
and
```json
{
   "circle": "99",
   "defaultLanguageLocationCode": "10"
}
```

@larubbio can you help disperse the fog?

**Comment by llavoie** [comment]
Spec bug?

**Comment by frankhuster** [comment]
Sounds good to me.
Another weirdness, /kilkari/user is supposed to return something like
```json
{
   "circle": "AA",
   "languageLocationCode": "10",
   "subscriptionPackList": []
}
```
but, because it inherits from ```UserResponse``` it actually returns
```json
{
   "languageLocationCode": "10",
   "defaultLanguageLocationCode": "10",
   "subscriptionPackList": [],
   "circle": "AA"
}
```
Note the extra ```defaultLanguageLocationCode``` data member. Do we care?

**Comment by llavoie** [comment]
Rob, will this impact the VXML? Or will it be ignored?

If it's ignored, we could probably live with it but open a low-priority bug
to address if we have time.

On Sat, Apr 25, 2015 at 12:48 PM, Frank Huster <notifications@github.com>
wrote:

> Sounds good to me.
> Another weirdness, /kilkari/user is supposed to return something like
>
> {
>    "circle": "AA",
>    "languageLocationCode": "10",
>    "subscriptionPackList": []
> }
>
> but, because it inherits from UserResponse it actually returns
>
> {
>    "languageLocationCode": "10",
>    "defaultLanguageLocationCode": "10",
>    "subscriptionPackList": [],
>    "circle": "AA"
> }
>
> Note the extra defaultLanguageLocationCode data member. Do we care?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koshalt/mim/issues/16#issuecomment-96271585>.
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by larubbio** [comment]
The spec is correct, when there is no user we return the default language for the circle and no subscriptionPackList.  

So if a user is found with subscriptions:

```javascript
{
   "languageLocationCode": "10",
   "defaultLanguageLocationCode": 99, // instead of null I would put the default code
   "subscriptionPackList": ["subscriptionOne", "blah"], // I'm not sure of the correct format
   "circle": "AA"
}
```

If a user is found without subscriptions:
```javascript
{
   "languageLocationCode": "10",
   "defaultLanguageLocationCode": 99, // instead of null I would put the default code
   "subscriptionPackList": [], 
   "circle": "AA"
}
```

If no user is found:
```javascript
{
   "languageLocationCode":  null,
   "defaultLanguageLocationCode": 99,
   "subscriptionPackList": [], 
   "circle": "AA"
}
```

According to the spec in the last two cases the subscriptionPackList key wouldn't be present, but that isn't the way the vxml is implemented.  

@llavoie having defaultLanguageCode when languageCode is set is ok.  They first check languageCode and if it isn't there use default.

**Comment by larubbio** [comment]
Also the issue with defaultLanguageCode is covered in #27

**Comment by frankhuster** [comment]
In the [current API spec](https://github.com/koshalt/mim/blob/master/specs/NMS%20API%20v1.2.pdf):
4.2.1.2 Get Subscriber Details API – Response
The expected response is
```json
{
   "circle": "AP",
   "languageLocationCode": "10",
   "subscriptionPackList": [
      "48WeeksPack",
      "72WeeksPack"
   ]
}
```
Note that ```defaultLanguageLocationCode``` is not present.
So doesn't that mean the spec is wrong, but the code is right?

**Comment by frankhuster** [comment]
Hmm, I think I understand what's going on.
The [current PDF spec](https://github.com/koshalt/mim/blob/master/specs/NMS%20API%20v1.2.pdf) is out of date since #27, right?
As a dev, in my day to day work, I only refer to the PDF. 
Seems hard to have to scan [all spec change issues](https://github.com/koshalt/mim/labels/spec%20change) in addition to that.
Should we have a much more simple & always updated google doc with the latest always up-to-date spec?

**Comment by koshalt** [comment]
That is precisely one of the reasons why I don't like PDF docs because they
feel static.

We should just try and keep the word doc in spec/ updated? Google drive
version sounds better too.

**Comment by larubbio** [comment]
The tickets are our _proposed_ spec changes.  What is in the pdf/doc is the
currently accepted spec.  In cases were we are implementing something
different from the spec we need to enter a ticket and label it so we can go
back and update the spec (and get agreement).

In this case I just happened to notice from reviewing the vxml code that
they also weren't in compliance with the spec.
