### ISSUE TITLE
NMS.KK.ACCESS.010 - Auto cancellation from MCTS upload

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#162]
Any of the events listed in #116  NMS.GEN.MCTS.008 related to events for mother/child shall lead to stopping of Kilkari service (subscription state = Deactivated).

The service shall stop immediately if maternal death, infant death, miscarriage or abortion is reported via MCTS

**Comment by larubbio** [comment]
![screen shot 2015-04-27 at 10 27 30 am](https://cloud.githubusercontent.com/assets/51527/7354207/892be780-ecce-11e4-8d4c-359a18b0d3b7.png)

**Comment by larubbio** [comment]
@llavoie Should this come into Sprint 2?  Seems similar to the LMP/DOB work you just did.

**Comment by llavoie** [comment]
Yes

**Comment by llavoie** [comment]
Actually, I think the existing SubscriptionService.deactivateSubscription(Subscription subscription, DeactivationReason reason) method is enough for now. This method would get called from the MCTS import code in sprint 3.
