### ISSUE TITLE
NMS.KK.ACCESS.011 - Scheduling of weekly messages

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#163]
Kilkari shall schedule the delivery of weekly messages to the beneficiary based on the activation date of the pack. Week is computed from LMP or DOB.

Also see comment in #157 NMS.KK.ACCESS.004.

**Comment by llavoie** [comment]
Notes to self:

- Create SubscriptionPackDetail object which maps weeks to messages
- Add a Lookup to Subscription that gets all active subs

**Comment by frankhuster** [comment]
I guess we need to coordinate what IMI really needs in the OBD targetFile to properly identity what content to play. If that is indeed a contentFileName, then I will need a function (probably best suited to be on a Subscription object) that, given a date will return a contentFileName for the subscription
