### ISSUE TITLE
NMS.KK.ACCESS.012 - Allowing change of schedule if DOB/LMP change

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#164]
Kilkari shall support change of schedule of weekly messages based on update of DOB/LMP.

**Comment by llavoie** [comment]
This ticket is potentially a can of worms and I'm trying to decide how many worms to let out. :)

Cases to think about:
- If DOB/LMP changes and user has an active child/pregnancy pack then we update the start date -- that part is clear.
- If user has a completed pack, but the date change would imply that the pack would still be active, should we reactivate? (I assume so -- or alternatively we could create a new subscription)
- If user has a deactivated pack, I assume the date change has no effect on subscriptions for that pack
- If a user has no subscriptions, should we create a subscription as a result of the date update?

**Comment by frankhuster** [comment]
Are these the kind of questions we should first decide to answer and then ask IMI or BBS about, or just ask IMI BBC?

**Comment by larubbio** [comment]
Asking for clarity isn't bad.  We probably should also provide suggestions.

My answers would be:

- Yes, update start date
- I would leave it completed.  That means they've heard the messages, so why send them again
- Agreed, leave it deactivated
- I think so.  If a DoB is added then I think that means they have a kid so we subscribe them

**Comment by llavoie** [comment]
I'll go with @larubbio 's answers for now (although I'm not sure I agree with the second point -- what if they have another kid/pregnancy?) because the code is relatively straightforward if I do. But I'll also flag this ticket for Pankaj to take a look in case he can help us get spec clarity/agreement.

**Comment by larubbio** [comment]
Would that come as a change of date, or as a new mcts upload?  You could
add logic and if the change of birthdate is more than 9 months then assume
it is a second kid.

**Comment by llavoie** [comment]
I'm not sure whether it would be a date change or new upload -- ideally a new upload because that case would be clear. For now I won't reactivate (or create new subscriptions) in the case of a completed subscription until we get more input.
