### ISSUE TITLE
NMS.KK.ACCESS.014 - Rule for marking subscription completed

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#166]
Kilkari service shall be completed after the Service Pack runs for its scheduled duration (subscription state = Completed).

**Comment by larubbio** [comment]
![screen shot 2015-04-27 at 10 27 30 am](https://cloud.githubusercontent.com/assets/51527/7354271/2b449864-eccf-11e4-8669-c24607a7d79e.png)

**Comment by llavoie** [comment]
Where do we get the data pertaining to the definition of packs?

**Comment by llavoie** [comment]
Assigning to @frankhuster because his pending pull request will fix this

**Comment by llavoie** [comment]
Reopening for now as @frankhuster is still refactoring this code.

**Comment by frankhuster** [comment]
Huh? But I'm the one who closed it. Am I missing something, @llavoie?

**Comment by frankhuster** [comment]
I guess today's pull request #246 did really do the job.

**Comment by llavoie** [comment]
You asked me to reopen this yesterday because you were still changing this code. :) Feel free to reclose if you're done.

**Comment by frankhuster** [comment]
Done!
