### ISSUE TITLE
NMS.KK.ACCESS.015 - Rules for managing subscription state

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#167]
Kilkari shall manage the subscription state as below:
- **Active**: Kilkari shall set the status of the subscription to “Active” on the start date of the subscribed pack.
- **Completed**: Kilkari shall set the status of the subscription to “Completed” after delivery (including retries if any) of the last message of the subscribed pack.
- **Deactivated**: Kilkari shall set the status of the subscription to “Deactivated” after a beneficiary has chosen the option to deactivate or due to other reasons ( #162  NMS.KK.ACCESS.010, #169 NMS.KK.OBD.008 & #170  NMS.KK.DND.002)
- **Pending Activation**: Kilkari shall set the status of the subscription to “Pending Activation” if the start date of the pack is in future.

**Comment by larubbio** [comment]
![screen shot 2015-04-27 at 10 27 30 am](https://cloud.githubusercontent.com/assets/51527/7353446/792d6d96-ecc8-11e4-9fcf-46332587bed5.png)

**Comment by frankhuster** [comment]
#243 takes care of #166 and the **Completed** state portion of this issue.

**Comment by llavoie** [comment]
I think the only part of this that isn't addressed yet is the transition from PENDING_ACTIVATION to ACTIVE.

**Comment by llavoie** [comment]
Should we have a SubscriptionActivator (similar to SubscriptionDeactivator) that is responsible for transitioning subscriptions from PENDING to ACTIVE once the subscriber reaches LMP + 90 days?

**Comment by llavoie** [comment]
We could add this to the OBD logic -- we'd need to change the target file generation to get all active and pending subscriptions due for a day (for now it only gets active), and update the pending ones to be active.
