### ISSUE TITLE
NMS.KK.OBD.008 - Deactivate if user phone number does not exist

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#169]
Kilkari service shall deactivate a user with appropriate deactivation cause if the error “user number does not exist” is received for all delivery attempts during a scheduling period for a message,

There is no point in delivery of a message to a non-existent number. Thus, after re-trying for finite number of times, the service shall be deactivated for that number.

**Comment by frankhuster** [comment]
Are we talking about the CDR process here?
So when the CDR processor receives OBD_FAILED_INVALIDNUMBER(2004) a certain number of times, it'll just deactivate all that subscriber's subscriptions?

**Comment by llavoie** [comment]
That sounds right.
