### ISSUE TITLE
NMS.KK.DND.002 - Rules for deactivation related to DND (Do Not Disturb)

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#170]
NMS shall mark a beneficiary as deactivated with associated reason if the beneficiary has its MSISDN number added to the DND database. This requirement applies to both cases listed below:
- The beneficiary is called for first time 
- The beneficiary has added its MSISDN number to the DND database while the OBD service is ongoing

In case a beneficiary removes its number from DND database, then such a use-case is currently not handled by the software.

**Comment by llavoie** [comment]
This comes into play when we get an entry in the CDR file indicating that the subscriber is in the DND -- in that case, we should set the beneficiary status (and subscription status?) to Deactivated.
