### ISSUE TITLE
NMS.KK.OBD.001 - Messages per week should be configurable

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#171]
Kilkari shall support the configurable number of messages per week, minimum 1 and maximum 2 per week.

**Comment by frankhuster** [comment]
Looks to me that we all play nicely with this one. Any reason that issue is still open?

**Comment by larubbio** [comment]
Do we have a place were that value can be set? @llavioe (or @lllllavioe I'm
never sure) pointed out that we will need to document how the different
config is set.

**Comment by llavoie** [comment]
I'm not sure what we have qualifies as "configurable" yet -- the default packs get into the DB via this method: https://github.com/motech-implementations/mim/blob/master/kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriptionServiceImpl.java#L55

I assume a bit more hard-coded than we'd like? If we're ok with this, then we can document how additional packs might be defined in the DB. Alternatively, I can alter this code to grab pack definitions from a config file.

**Comment by larubbio** [comment]
Does that code create the pregnancy pack with 2 messages per week?  Is that
correct?

**Comment by llavoie** [comment]
For now it assumes that pregnancy pack is 2/week and child pack is 1/week. I haven't seen any definitive info about this in any spec, so those are temporary assumptions...

**Comment by larubbio** [comment]
We should get clarity, but I always though it was 1 per week with the option to move to 2 .  

cc @pankajnagpal30

**Comment by llavoie** [comment]
Ok -- easy to change once we hear from Pankaj. I'll add this to the questions doc too.

**Comment by llavoie** [comment]
Change the code to not create the packs -- ops will need to create them in the DB
