### ISSUE TITLE
NMS.KK.IVR.002 - Different welcome message for "Early Subscription"

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#176]
Kilkari shall play a different welcome message for the beneficiary who accesses the Inbox and has “Early Subscription” subscribed via MCTS upload which is not activated yet.

Refer #160  NMS.KK.ACCESS.007 for description of “Early Subscription”.

**Comment by llavoie** [comment]
In discussion with IMI and Aricent. We could either return no message or the subscription status in the InboxResponse.

**Comment by frankhuster** [comment]
Fixed by #246
