### ISSUE TITLE
NMS.KK.DND.001 - DND database

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#180]
NMS shall not initiate any OBD call to a beneficiary if the beneficiary has the MSISDN registered in the DND database and the activation has happened via MCTS import.

The DND restriction does not apply for those beneficiary that have activated via the IVR.

To realize this requirement, NMS system shall maintain a DND database. The exact mechanism to realize the DND database is outside the scope of this document.

The DND restrictions apply to OBD call for Kilkari service only. They do not apply to incoming services like MA and MK. For MA, it also does not apply to course-completion SMS.

**Comment by larubbio** [comment]
There may not be work for this item.  I've emailed IMI to ask about their DND handling.

**Comment by larubbio** [comment]
From the email thread:

    The handling for following requirement is missing in API document. To fulfill this requirement, 
    a new field is needed in OBD record to convey the source of kilkari subscription i.e. IVR/MCTS. 
    Please let me know, if this change is fine with you.

**Comment by llavoie** [comment]
My current in-progress change adds a "subscription mode" to the subscription, with values IVR and MCTS_UPLOAD. The mode is passed at subscription time (the REST API always passes IVR) and certain behavior is determined by it (e.g. rules for rejecting subscriptions detailed in #159).

**Comment by llavoie** [comment]
@frankhuster  You'll want to add one more column to the OBD target file you are generating, which contains the Subscriber.subscriptionMode (IVR or MCTS).
