### ISSUE TITLE
NMS.KK.DND.002 - Deactivate beneficiaries added to DND database

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#181]
NMS shall mark a beneficiary as deactivated with associated reason if the beneficiary has its MSISDN number added to the DND database. This requirement applies to both cases listed below:
- The beneficiary is called for first time 
- The beneficiary has added its MSISDN number to the DND database while the OBD service is ongoing

In case a beneficiary removes its number from DND database, then such a use-case is currently not handled by the software.

**Comment by llavoie** [comment]
duplicate of #170
