### ISSUE TITLE
NMS.KK.DND.003 - Allow a user who deactivated via DND to re-activate via IVR

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#182]
NMS shall allow a subscriber deactivated due to DND restrictions to activate the Kilkari service again via IVR.

**Comment by llavoie** [comment]
This should "just work" if we implement the DND logic correctly, but it would be worth adding a test for this.

**Comment by larubbio** [comment]
If IMI is handling DND then we have no work for this.

**Comment by llavoie** [comment]
I agree, but it might be worth adding a test for this use case just to be safe.

-----Original Message-----
