### ISSUE TITLE
NMS.KK.SCALE.003 - Cap kilkari subscribers to prevent overloading of IVR

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#183]
The Congestion and Overload for outgoing calls of KK shall be handled by maintaining a configurable parameter to limit number of active KK subscribers. Once this limit is reached, new subscribers activation shall not be allowed (either via CSV upload or via IVR based activation).

Rejection of uploaded subscribers due to over-capacity shall be logged.

The “early subscription” shall be considered as part of active subscriber list for purpose of calculation.
In some cases, it can reject more users than it could have handled (e.g. due to early subscription).

**Comment by llavoie** [comment]
Pausing work on this until we decide whether or not to drop this requirement. In-progress change is in branch 183.

**Comment by frankhuster** [comment]
@llavoie what's the status of this issue?

**Comment by llavoie** [comment]
@frankhuster We need to have a discussion with Saurabh about it, but current thought is that we might not do it.

**Comment by llavoie** [comment]
Moving to sprint 4 because we are still discussing whether this feature will happen.

**Comment by larubbio** [comment]
Discussed on the monday night call.  Sara said we can set the cap to 58 million. i.e. no cap.

**Comment by llavoie** [comment]
Woot!

On Mon, Jul 6, 2015 at 10:49 PM, Rob LaRubbio <notifications@github.com>
wrote:

> Closed #183 <https://github.com/motech-implementations/mim/issues/183>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/183#event-349339123>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*
