### ISSUE TITLE
72WeeksPack or 76WeeksPack?

### ISSUE THREAD

**Issue by frankhuster** [motech-implementations/mim#189]
I saw references to both in the spec.

**Comment by llavoie** [comment]
Based on this comment in the SRS:

> 3Jan15: MOHFW has confirmed that there will be 2 packs. 72 week pack- 
> starting from 2nd trimester till the child is of 12 month age. 48 week pack –
> starting from the child birth till the child is of 12 month age.

I assume that at some point a 76-week pack was discussed, but that the MOH decided on the 72-week pack. Note that the SRS fairly consistently talks about a 72 week pack, but the API spec is sloppy about this, and has many references to both 76 and 72.

**Comment by frankhuster** [comment]
On Fri, May 1, 2015 at 12:55 PM, Lauren Lavoie <notifications@github.com>
wrote:

> 2nd trimester till the child is of 12 month age


Hmm, interesting...

I always thought there was ​one antenatal and one postnatal campaign.

But it's really two postnatal campaigns where one starts at birth and one
starts at pregnancy.

...interesting...






-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by llavoie** [comment]
Technically you could say that one is postnatal and the other is prenatal + postnatal :)

**Comment by frankhuster** [comment]
Kamalika says: 
> This service is a 72 week pack. But the data around the service provided to the mother needs to be kept online for 6 additional weeks beyond the 72 weeks - hence for disk sizing purposes, data will occupy space for 78 weeks. The data can then be archived and must be stored for 3 years.

**Comment by frankhuster** [comment]
How about calling packs by their names, not their sizes?
**child pack** and **pregnancy pack**

*size doesn't matter*
