### ISSUE TITLE
Should getSubscriptions return only ACTIVE subscriptions, or ACTIVE and PENDING_ACTIVATION?

### ISSUE THREAD

**Issue by llavoie** [motech-implementations/mim#199]
We can probably get the answer to this from reviewing the VXML.

**Comment by larubbio** [comment]
The IVR only looks at the first two subscription packs returned.  We never send the status, so we should filter that list to only include open subscriptions.

For inbox, they iterate over the subscriptions and play the message.  If we send a subscription without "!lSubscriptionPack || !lInboxWeekId || !lContentFileName" if it is the first in the list they will play the promo message and never play the second.  So on that api we should only return subscriptions with messages (although there is a req about playing a message if it is an early subscription, but there is no prompt for that currently and the vxml does not support it)

**Comment by llavoie** [comment]
Ok, perfect. Thanks for checking.

**Comment by larubbio** [comment]
Although we still have some work for this, and we should add tests that create deactivated subscriptions and post to the kilkari apis

**Comment by llavoie** [comment]
Verify that we're good to go here, there might not be anything to do.

**Comment by llavoie** [comment]
Fixed
