### ISSUE TITLE
What should MOTECH do when we receive a file processed error?

### ISSUE THREAD

**Issue by frankhuster** [motech-implementations/mim#200]
Scenario
we create a target file and the IVR system returns any of the following
    FILE_NOT_ACCESSIBLE(8001),
    FILE_CHECKSUM_ERROR(8002),
    FILE_RECORDSCOUNT_ERROR(8003),
    FILE_OUTSIDE_SOCIAL_HOURS(8004),
    FILE_ERROR_IN_FILE_FORMAT(8005);
In addition to logging an error and possibly creating a MOTECH alert, what to we do?

@larubbio suggested maybe a /status page...

**Comment by larubbio** [comment]
@frankhuster Any answer on this?  If not can you move the issue forward or close it.

**Comment by frankhuster** [comment]
Confirming we do create a log error and and a MOTECH alert.
