### ISSUE TITLE
Harmonize cross-module data service use

### ISSUE THREAD

**Issue by frankhuster** [motech-implementations/mim#209]
There are two ways for modulea to access moduleb's entities:
1- directly use the ModuleaSomeEntityDataService that's generated by MDS.
2- have modulea explicitely create a service class with whatever is needed and have moduleb use the service class.

We need to decide which it is and make sure all modules adhere to that decision.

**Comment by larubbio** [comment]
I'm closing tickets that we realistically aren't going to get to.  This is one of them.
