### ISSUE TITLE
Consider using bean Validation instead of 'hand validating' API constraints?

### ISSUE THREAD

**Issue by frankhuster** [motech-implementations/mim#215]
Should we look at [annotating service API methods using annotations](https://docs.jboss.org/hibernate/validator/4.0.1/reference/en-US/html/validator-usingvalidator.html) and have them automagically handled instead of doing it *by hand*?

**Comment by koshalt** [comment]
I got a little further along on this but realized that we have a problem with how we return errors in the current scheme. 

With a field marked as @NotNull and @Valid annotation on the API method, we wouldn't necessarily have a way to return <foobar: Invalid> type responses to calls.

Taking it a step further, the current design of return <%s:%s> is only really helpful during the first couple of integration deployments, right? I don't expect IMI to switch on these return codes during live prod deployment?

**Comment by larubbio** [comment]
What is the issue with returning type responses?

We should be able to access field by field responses from the validator (
http://stackoverflow.com/questions/24811643/spring-bean-validation-valid-handling)
or write our own customer validation, or even specify the message to return
via something like @NotNull(message = "<name: Invalid/>")

**Comment by larubbio** [comment]
I'm closing tickets that we realistically aren't going to get to.  This is one of them.
