### ISSUE TITLE
Upload languageLocationCodes

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#218]
Issue #119 has several features within it.  This one should be handled as it's own task:

> There shall be one and only one “Language-location code” used in a given geographical location.
> This “Language-location code” shall be same and applicable to all services in that location.

**Comment by llavoie** [comment]
@larubbio please add CSV schema info

**Comment by larubbio** [comment]
![screen shot 2015-05-06 at 11 11 01 am](https://cloud.githubusercontent.com/assets/51527/7618354/86a9ea12-f966-11e4-93cd-4a50c84a25b4.png)

**Comment by larubbio** [comment]
Below is data from the sample file that was mailed to me over the weekend.  I think we need to modify the domain entity so there is a many to many relationship between circle and language location code.  I'm also confused about the value of this table.

Circle | State | District | languagelocation code | Language | Default Language for Circle (Y/N)
-------|-------|----------|-----------------------|----------|----------------------------------
Delhi - NCR | Delhi | North District | HIN | Hindi | Y
Delhi - NCR | Delhi | Central District | HIN | Hindi | Y
Delhi - NCR | Delhi | South District | HIN | Hindi | Y
Delhi - NCR | Delhi | New Delhi District | HIN | Hindi | Y
Delhi - NCR | Delhi | West District | HIN | Hindi | Y
Delhi - NCR | Delhi | North East District | HIN | Hindi | Y
Delhi - NCR | Delhi | East District | HIN | Hindi | Y
Delhi - NCR | Delhi | North West District | HIN | Hindi | Y
Delhi - NCR | Delhi | South East District | HIN | Hindi | Y
Delhi - NCR | Delhi | SHAHDARA | HIN | Hindi | Y
Delhi - NCR | Delhi | Shahdara District | HIN | Hindi | Y
UPEast | Uttar Pradesh | Allahabad | HIN | Hindi | Y
UPEast | Uttar Pradesh | Azamgarh | HIN | Hindi | Y
UPEast | Uttar Pradesh | Bahraich | HIN | Hindi | Y
UPEast | Uttar Pradesh | Ballia | HIN | Hindi | Y
UPEast | Uttar Pradesh | Balrampur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Banda | HIN | Hindi | Y
UPEast | Uttar Pradesh | Barabanki | HIN | Hindi | Y
UPEast | Uttar Pradesh | Basti | HIN | Hindi | Y
UPEast | Uttar Pradesh | C S Nagar | HIN | Hindi | Y
UPEast | Uttar Pradesh | Chandauli | HIN | Hindi | Y
UPEast | Uttar Pradesh | Chitrakoot | HIN | Hindi | Y
UPEast | Uttar Pradesh | Deoria | HIN | Hindi | Y
UPEast | Uttar Pradesh | Faizabad | HIN | Hindi | Y
UPEast | Uttar Pradesh | FARRUKHABAD | HIN | Hindi | Y
UPEast | Uttar Pradesh | Fatehpur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Gazipur | HIN | Hindi | Y
UPEast | Uttar Pradesh | GB Nagar | HIN | Hindi | Y
UPEast | Uttar Pradesh | Gonda | HIN | Hindi | Y
UPEast | Uttar Pradesh | Gorakhpur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Hamirpur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Hardoi | HIN | Hindi | Y
UPEast | Uttar Pradesh | Jalaun | HIN | Hindi | Y
UPEast | Uttar Pradesh | Jaunpur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Jhansi | HIN | Hindi | Y
UPEast | Uttar Pradesh | Kannauj | HIN | Hindi | Y
UPEast | Uttar Pradesh | Kanpur Dehat | HIN | Hindi | Y
UPEast | Uttar Pradesh | Kanpur Nagar | HIN | Hindi | Y
UPEast | Uttar Pradesh | Kaushambi | HIN | Hindi | Y
UPEast | Uttar Pradesh | Kushinagar | HIN | Hindi | Y
UPEast | Uttar Pradesh | Lakhimpur Kheri | HIN | Hindi | Y
UPEast | Uttar Pradesh | Lalitpur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Lucknow | HIN | Hindi | Y
UPEast | Uttar Pradesh | Maharajganj | HIN | Hindi | Y
UPEast | Uttar Pradesh | Mahoba | HIN | Hindi | Y
UPEast | Uttar Pradesh | Mau | HIN | Hindi | Y
UPEast | Uttar Pradesh | Mirzapur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Pratapgarh | HIN | Hindi | Y
UPEast | Uttar Pradesh | Raibareilly | HIN | Hindi | Y
UPEast | Uttar Pradesh | Sant Kabir Nagar | HIN | Hindi | Y
UPEast | Uttar Pradesh | Shahjanpur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Sharawasti | HIN | Hindi | Y
UPEast | Uttar Pradesh | Siddharth nagar | HIN | Hindi | Y
UPEast | Uttar Pradesh | Sitapur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Sonebhadra | HIN | Hindi | Y
UPEast | Uttar Pradesh | SRN Bhadohi | HIN | Hindi | Y
UPEast | Uttar Pradesh | Sultanpur | HIN | Hindi | Y
UPEast | Uttar Pradesh | Unnao | HIN | Hindi | Y
UPEast | Uttar Pradesh | Varanasi | HIN | Hindi | Y
UPWest | Uttar Pradesh | Agra | HIN | Hindi | Y
UPWest | Uttar Pradesh | Aligarh | HIN | Hindi | Y
UPWest | Uttar Pradesh | Ambedhkar Nagar | HIN | Hindi | Y
UPWest | Uttar Pradesh | Amroha | HIN | Hindi | Y
UPWest | Uttar Pradesh | Auraiya | HIN | Hindi | Y
UPWest | Uttar Pradesh | Badaun | HIN | Hindi | Y
UPWest | Uttar Pradesh | Baghpat | HIN | Hindi | Y
UPWest | Uttar Pradesh | Bareilly | HIN | Hindi | Y
UPWest | Uttar Pradesh | Bijnor | HIN | Hindi | Y
UPWest | Uttar Pradesh | Bulandshahr | HIN | Hindi | Y
UPWest | Uttar Pradesh | Etah | HIN | Hindi | Y
UPWest | Uttar Pradesh | Etawah | HIN | Hindi | Y
UPWest | Uttar Pradesh | Firozabad | HIN | Hindi | Y
UPWest | Uttar Pradesh | Ghaizabad | HIN | Hindi | Y
UPWest | Uttar Pradesh | Hapur | HIN | Hindi | Y
UPWest | Uttar Pradesh | Hathras | HIN | Hindi | Y
UPWest | Uttar Pradesh | Kasganj | HIN | Hindi | Y
UPWest | Uttar Pradesh | Mainpuri | HIN | Hindi | Y
UPWest | Uttar Pradesh | Mathura | HIN | Hindi | Y
UPWest | Uttar Pradesh | Meerut | HIN | Hindi | Y
UPWest | Uttar Pradesh | Moradabad | HIN | Hindi | Y
UPWest | Uttar Pradesh | Muzaffarnagar | HIN | Hindi | Y
UPWest | Uttar Pradesh | Pilibhit | HIN | Hindi | Y
UPWest | Uttar Pradesh | Rampur | HIN | Hindi | Y
UPWest | Uttar Pradesh | Saharanpur | HIN | Hindi | Y
UPWest | Uttar Pradesh | Sambhal | HIN | Hindi | Y
UPWest | Uttar Pradesh | Shamli | HIN | Hindi | Y
UPWest | Uttarakhand | Haridwar | HIN | Hindi | Y
UPWest | Uttarakhand | Dehradun | HIN | Hindi | Y
UPWest | Uttarakhand | Udham Singh Nagar | HIN | Hindi | Y
UPWest | Uttarakhand | Nainital | HIN | Hindi | Y
UPWest | Uttarakhand | Pauri Garhwal | HIN | Hindi | Y
UPWest | Uttarakhand | Almora | HIN | Hindi | Y
UPWest | Uttarakhand | Tehri Garhwal | HIN | Hindi | Y
UPWest | Uttarakhand | Pithoragarh | HIN | Hindi | Y
UPWest | Uttarakhand | Chamoli | HIN | Hindi | Y
UPWest | Uttarakhand | Uttarkashi | HIN | Hindi | Y
UPWest | Uttarakhand | Bageshwar | HIN | Hindi | Y
UPWest | Uttarakhand | Champawat | HIN | Hindi | Y
UPWest | Uttarakhand | Rudraprayag | HIN | Hindi | Y
Odisha | Odisha | BALANGIR | ORI | Odiya | Y
Odisha | Odisha | BOUDH | ORI | Odiya | Y
Odisha | Odisha | GAJAPATI | ORI | Odiya | Y
Odisha | Odisha | KALAHANDI | ORI | Odiya | Y
Odisha | Odisha | KANDHAMAL | ORI | Odiya | Y
Odisha | Odisha | KORAPUT | ORI | Odiya | Y
Odisha | Odisha | MALKANGIRI | ORI | Odiya | Y
Odisha | Odisha | NABARANGAPUR | ORI | Odiya | Y
Odisha | Odisha | NUAPADA | ORI | Odiya | Y
Odisha | Odisha | RAYAGADA | ORI | Odiya | Y
Odisha | Odisha | ANGUL | ORI | Odiya | Y
Odisha | Odisha | BALASORE | ORI | Odiya | Y
Odisha | Odisha | BARGARH | ORI | Odiya | Y
Odisha | Odisha | BHADRAK | ORI | Odiya | Y
Odisha | Odisha | CUTTACK | ORI | Odiya | Y
Odisha | Odisha | DEOGARH  | ORI | Odiya | Y
Odisha | Odisha | DHENKANAL | ORI | Odiya | Y
Odisha | Odisha | GANJAM | ORI | Odiya | Y
Odisha | Odisha | JAGATSINGHPUR  | ORI | Odiya | Y
Odisha | Odisha | JAJPUR | ORI | Odiya | Y
Odisha | Odisha | JHARSUGUDA | ORI | Odiya | Y
Odisha | Odisha | KENDRAPARA | ORI | Odiya | Y
Odisha | Odisha | KEONJHAR | ORI | Odiya | Y
Odisha | Odisha | KHURDA | ORI | Odiya | Y
Odisha | Odisha | MAYURBHANJ | ORI | Odiya | Y
Odisha | Odisha | NAYAGARH | ORI | Odiya | Y
Odisha | Odisha | PURI | ORI | Odiya | Y
Odisha | Odisha | SAMBALPUR | ORI | Odiya | Y
Odisha | Odisha | SONEPUR | ORI | Odiya | Y
Odisha | Odisha | SUNDARGARH | ORI | Odiya | Y

**Comment by kamknitt** [comment]
Since states and districts are identified by their names, can we assume that they are unique? I think that it is safe to assume so for a state, but after seeing names like "North District" I'm not sure of it in the case of a district.

**Comment by larubbio** [comment]
@kamknitt Is this issue complete?
