### ISSUE TITLE
OBD needs to indicate when a welcome message should be played rather than the first message in the pack

### ISSUE THREAD

**Issue by llavoie** [motech-implementations/mim#221]
Breaking this out into a separate issue from #157, which deals mostly with setting subscription start dates.

Handling for following requirement is missing in API specification. 

"If a woman is subscribed to Kilkari via MCTS data, the service could start at any point during the 72
week or 48 week schedule. Since we cannot assume that her ASHA or ANM will have informed her
about Kilkari, we will need to play her an initial welcome message before any other content is played."

To handle this requirement a new field is needed in OBD record (in OBD file) to indicate the first 
OBD message of subscribed pack.

**Comment by llavoie** [comment]
The pull request referenced above adds a "needsWelcomeMessage" field to Subscription, and sets it to true for a new MCTS subscription. The CDR processor will need to set this field to false once the subscriber has received the welcome message. Assigning to @frankhuster.

**Comment by frankhuster** [comment]
Fixed by #246
