### ISSUE TITLE
NMS.MA.COURSE.002 - Course completion criteria followup

### ISSUE THREAD

**Issue by koshalt** [motech-implementations/mim#245]
There are a few edge cases in #149 that need some clarity and might have some follow up work based on the response from BBC.

These edge cases have to deal with when happens a when a user fails a course with his/her score and the resetting of bookmarks upon completion.

**Comment by larubbio** [comment]
When we get the response we should also update the spec.

**Comment by koshalt** [comment]
clarification from bbc -

1.    There is no workflow from a completed course state to restarting the course again. This means that the next time an FLW calls in, they start out like a new user (as opposed to playing an ivr message saying we noticed you finished the course, do you want to restart, etc)

When any FLW restart the course, system should take him as new user only, scripts of prompts need to be played is given below.

2.    Pass Citeria
This is always the total score right? If the user got a 0 in 5 of the chapters but scored great in the rest to make up for the 22 needed to pass, they are still considered passing?

Yes this understanding is correct.

3. What should we do if a user completes a course but fails the pass criteria of > 50% score? 
- Do they get an option to restart the course or quiz? – details mentioned below.
- Do we not reset their bookmarks? – yes bookmarking has to be reset.
- Who makes this decision? (IVR vs motech) – I believe all scores are saved in Motech.
 
After quiz completion of 11th chapter below prompts will play.
 
Prompt 1-
Congratulations on successfully completing the training course. Out of maximum possible 44 marks you have scored <XX marks>
 
Prompt 2A (if user have >= 50% marks)
I am happy to say that now you can get your certificate. In a few minutes, you will receive an SMS on your mobile. Take this SMS to your monthly sub-center meeting and show it to the Community Coordinator. They will give you your certificate.
 
Prompt 2B (if user have < 50% marks)
You may do the course once again to improve on your score and earn a certificate. Just call 5771102 to start the course again from the beginning.
