### ISSUE TITLE
SRS 8.4.1 Kilkari Individual Reports - Need clarity

### ISSUE THREAD

**Issue by frankhuster** [motech-implementations/mim#255]
The *Weekly messages for MSISDN* detailed report specifies (among other) the following 3 fields:

- NA Count
- ND Count
- SO Count

But what MOTECH gets back from IMI is one of the following (API 4.5.1 OBD Status-Codes):

- OBD_SUCCESS_CALL_CONNECTED
- OBD_FAILED_NOATTEMPT
- OBD_FAILED_BUSY
- OBD_FAILED_NOANSWER
- OBD_FAILED_SWITCHEDOFF
- OBD_FAILED_INVALIDNUMBER
- OBD_FAILED_OTHERS
- OBD_DNIS_IN_DND

How should MOTECH map the latter to the former?

**Comment by larubbio** [comment]
Does MOTECH have to map this or does the reporting code?  

@frankhuster is there anything for us to do on this ticket?  If not please close

**Comment by llavoie** [comment]
@frankhuster ?

**Comment by frankhuster** [comment]
Given we're now saving all CDRs from IMI, it's fine to close this.
