### ISSUE TITLE
Sms content for course completion

### ISSUE THREAD

**Issue by koshalt** [motech-implementations/mim#278]
Started 2 threads with both bbc and imi but no resolution yet. The functional spec says the content with be in english characters but phonetically in the user's language. I'm still not sure where we would get that content from.

@pankajnagpal30 can you follow up?

**Comment by llavoie** [comment]
Btw, I don't think Pankaj sees @ mentions from github. It looks like he hasn't accepted the invite to the project. So best to email or catch him on Skype.

-----Original Message-----

**Comment by koshalt** [comment]
Sounds good @llavoie . Will add it to the google doc for tracking as well

**Comment by pankajnagpal30** [comment]
Hi Kosh,I am not able to understand the Question correctly. Can you please explain it to get this clarified.

**Comment by koshalt** [comment]
When a user completes a course, we send them an sms saying they have
successful completed the course. The user then take this to their
supervisor/manager who then issues a certificate.

According to the current POR, the sms will be in english alphabet but
phonetically spelled in the user's language. However, we have not
identified what the actual content of the sms will be and/or who (imi vs
motech) stores it.

Let me know if that makes sense. Thanks.

**Comment by koshalt** [comment]
Tracking with #284
