### ISSUE TITLE
Host and serve localized sms content for course completion

### ISSUE THREAD

**Issue by koshalt** [motech-implementations/mim#284]
Based on recent thread with BBC - 

Looks like we will need to host the sms content for all the different language codes (transliterated to english) and send the course completion sms notification with this content.

TODO -
1. ingest and store content (based on llc)
2. Based on the users llc at completion, choose the appropriate content to send and call IMI

**Comment by larubbio** [comment]
Would the content be associated with llc (currently undefined) or with the language code?  If they user speaks hindi in bihar would that content be different than if the user spoke hindi in delhi?  (I don't think so, we should verify)
