### ISSUE TITLE
Kilkari: Consider removing bi-directionality of Subscriber-Subscription relationship

### ISSUE THREAD

**Issue by llavoie** [motech-implementations/mim#31]
This relationship is bidirectional because MDS doesn't yet support Lookups based on relationship fields. Once https://applab.atlassian.net/browse/MOTECH-1638 is fixed, we could remove Subscriber.subscriptions (and keep Subscription.subscriber).

**Comment by larubbio** [comment]
I'm closing issues that we most likely will not get to.  This is one.

I also think having that as a bi-directional relationship is useful
