### ISSUE TITLE
Return a 404 if Kilkari subscriber not found

### ISSUE THREAD

**Issue by llavoie** [motech-implementations/mim#34]
For the GetInboxDetails and GetUserDetails APIs (and likely others), we'd like to return a 404 if the callingNumber does not resolve to an actual user. This is missing from the spec.

**Comment by larubbio** [comment]
GetUserDetails does not return a 404 if the user isn't found.

**Comment by llavoie** [comment]
I believe GetInboxDetails does though. What do we want to do? 404 makes sense to me.

**Comment by larubbio** [comment]
Yep, I'm adding that to the spec now.
