### ISSUE TITLE
Type error in All Api request coming from IVR to NMS

### ISSUE THREAD

**Issue by srivastavaAbhi** [motech-implementations/mim#395]
NMS shall return only Http error code  400 for all the type error in parameter of Api request send by IVR to NMS and error string shall contains only spring framework error/JSON parser error.

As per API document, NMS should send  "<Parameter name : Invalid value>" with http error code  400.

@koshalt : Please confirm.

**Comment by koshalt** [comment]
I agree. This confirms that in the cases where the url parameter type is incorrect, we rely on Spring framework to automatically fail validation and send back a 400. We will not write handlers to intercept the spring exception to return the <parameter: invalid> format response.

We should just update the API spec to mention this.

**Comment by larubbio** [comment]
Won't fix ether the code or spec now.
