### ISSUE TITLE
Provide status page(s) for monitoring

### ISSUE THREAD

**Issue by llavoie** [motech-implementations/mim#437]

**Comment by frankhuster** [comment]
provide http endpoint in API module that queries the MOTECH alerts

**Comment by frankhuster** [comment]
[Changed the platform's alerts module](http://review.motechproject.org/#/c/5463/) to provide HTTP endpoints to query for alert counts.

**Comment by frankhuster** [comment]
This will be fixed as soon as http://review.motechproject.org/#/c/5463/ is reviewed & merged.
