### ISSUE TITLE
CdrFileServiceBundleIT.testProcess is flaky

### ISSUE THREAD

**Issue by llavoie** [motech-implementations/mim#448]
This test fails sporadically for me.

Tests run: 465, Failures: 1, Errors: 0, Skipped: 42, Time elapsed: 235.396 sec <<< FAILURE! - in org.motechproject.nms.testing.it.IntegrationTests
testProcess(org.motechproject.nms.testing.it.imi.CdrFileServiceBundleIT)  Time elapsed: 3.068 sec  <<< FAILURE!
java.lang.AssertionError: Timeout while waiting for CSR processing
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.motechproject.nms.testing.it.imi.CdrFileServiceBundleIT.testProcess(CdrFileServiceBundleIT.java:239)

Results :

Failed tests: 
  CdrFileServiceBundleIT.testProcess:239 Timeout while waiting for CSR processing

**Comment by larubbio** [comment]
![](http://www.reactiongifs.com/r/abwha1.gif)

**Comment by larubbio** [comment]
![](http://www.reactiongifs.com/r/irdc.gif)

**Comment by larubbio** [comment]
![](http://www.reactiongifs.com/r/dsb.gif)

**Comment by larubbio** [comment]
![](http://www.reactiongifs.com/r/mnc.gif)

**Comment by koshalt** [comment]
![trs](https://cloud.githubusercontent.com/assets/6786794/8705704/2f8bdfbe-2ae0-11e5-93b1-9212a4e7a028.gif)

**Comment by llavoie** [comment]
At some point it was failing relatively regularly for me. If that's not happening for you guys -- or it doesn't bother you -- feel free to close the ticket.

-----Original Message-----

**Comment by larubbio** [comment]
It bothers me.  It doesn't bother Adrian Brody, Alec Baldwin, John C. Reilly & John C. McGinley.  Alice appears to be inconsolable over it.

**Comment by koshalt** [comment]
![trmp](https://cloud.githubusercontent.com/assets/6786794/8712418/d9c12d24-2b10-11e5-874c-e417e5f2f90f.gif)

Don't forget the trumpster

**Comment by larubbio** [comment]
Trump hate flaky test!

**Comment by frankhuster** [comment]
Frankie hate flaky test too, but is having a hard time getting `CdrFileServiceBundleIT#testProcess` to fail.
However, I've seen `TargetFileServiceBundleIT#testTargetFileGeneration` fail mysteriously, so working on that...

**Comment by larubbio** [comment]
Let's set this aside for a bit and look at one of the integration tickets
first.  NIP-53 should be a good one to start with.

**Comment by frankhuster** [comment]
Sounds good

**Comment by frankhuster** [comment]
Hasn't flaked in, like, forever...
