### ISSUE TITLE
NMS.GEN.LOG.010 - Audit trail logging via MDS UI

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#475]
NMS system shall have audit trail logs that includes but not limited to the following:

- Any changes via MDS UI

The audit trail log shall include event details, date/time of event and user credential information among others.

**Comment by kamknitt** [comment]
What do we mean by "any change via MDS UI"? Is it literally any change or any change done to NMS entities (or some of them)? Does ChangeLog record introduced with changes tracking feature counts as audit trail log?

**Comment by larubbio** [comment]
It would be any change to an NMS entity.  Yes, the ChangeLog record counts
as an audit trail log.

**Comment by larubbio** [comment]
@kamknitt Do you have ideas on how to implement this?  Also any status on it?

**Comment by kamknitt** [comment]
It requires http://review.motechproject.org/#/c/5415/ to be merged. Then we can use the changes tracking feature and annotate all NMS entities as tracked.

**Comment by larubbio** [comment]
I reviewed and merged that change.  I don't think we need to add this to any other entities, so we should be able to resolve this now.
