### ISSUE TITLE
NMS.GEN.LOG.007 - Location record history tracking (collections only)

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#506]
NMS system shall maintain history of all changes done in a given Location record via code. 

Tracking of changes via UI is tracked in #475

Tracking of non-collection fields is tracked #139

**Comment by larubbio** [comment]
@kamknitt Just wanted to check in to see how the implementation was going.

**Comment by larubbio** [comment]
@kamknitt Actually on the project planning call it was decided that we can drop this feature.  (This is just for many to many relationships correct?)

**Comment by kamknitt** [comment]
@larubbio It is also related with one-to-many if the collection is modified at the 'many' side (for example: author.getBooks().add(book);). In this situation the changes are not tracked too. I've managed however to got it to work with an approach described in #139: https://github.com/motech-implementations/mim/pull/515
