### ISSUE TITLE
Taluka many-to-many HealthBlock

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#595]
1) Location mapping of Talukas and Blocks is one to many (slide 5 in the attached ppt). 

In other words, one health block can be mapped to multiple talukas and one taluka can be mapped to multiple health blocks. In addition, one village can be mapped to multiple sub-centers, and one PHC can be mapped to multiple CHCs.

According to the MCTS team at MoHFW, they shared the MCTS location master data sheet with GF many months ago (I remember being in a meeting with Pankaj, Rajat C and Suparna in January I think when we asked MoHFW to send us the location master data sheet).

Did you ever get the MCTS Master Location Data sheet? Because according to the MCTS team, it clearly shows the one to many location mapping relationship between blocks and talukas and villages and sub-centers and PHCs and CHCs.

I have not attended any of the many meetings with the MCTS team since that initial meeting in Jan - but it seems that this may not have been discussed.

In addition, when you look at the fields that Aricent has highlighted in yellow on slide 7, which Aricent said were not necessary, you will see that these are the location mapping fields that handle the one to many mapping of blocks to talukas, sub-centers to villages and PHCs to CHCs.

The MCTS team didn't understand why we wouldn't want these fields, since they are required for the one to many mapping.

At any rate, it looks like we will have to change the mapping logic in Motech if we want to get any data below the district level into the DB. And clearly this will have an impact on the design of Pentaho...

**Comment by larubbio** [comment]
[MCTS Data concerns v0.2.pptx](https://github.com/motech-implementations/mim/files/4499/MCTS.Data.concerns.v0.2.pptx)

**Comment by frankhuster** [comment]
So, should the object model be something like:
```
Class District {
   ...
   Set<Taluka> talukas,
   Set<HealthBlock> healthBlocks,
   ...
}

Class Taluka {
   ...
   District district,
   Set<HealthBlock> healthBlocks,
   ...
}

Class Set<HealthBlock> {
   ...
   District district,
   Set<Taluka> talukas,
   ...
}
```

**Comment by larubbio** [comment]
This drive folder has the schemas:

https://drive.google.com/drive/u/1/folders/0B6TZ7g-U-3SdfmpQSVJvaHc5MnNlR1Vob0NrZFBHbmVOVzk2RWkyTzFSQUxZdklCVHo5S2s

I'm assuming we should ignore the Taluka Code (T_Code) in the HealthBlock table and instead use 'HealthBlock_Taluka_Mapping_Master'

![screen shot 2015-09-29 at 3 12 46 pm](https://cloud.githubusercontent.com/assets/51527/10179703/93a688ce-66bc-11e5-9f60-c8ec1ceac69f.png)

**Comment by larubbio** [comment]
We need to verify that if we delete 

```
    @Field
    @Column(allowsNull = "false")
    @NotNull
    @JsonBackReference
    private Taluka taluka;
```

From HealthBlock.java and replace it with

```
    @Field
    @JsonBackReference
    private List<Taluka> talukas;
```

and change this in Taluka.java

```
    @Field
    @Cascade(delete = true)
    @Persistent(mappedBy = "taluka", defaultFetchGroup = "true")
    @JsonManagedReference
    private List<HealthBlock> healthBlocks;
```

to

```
    @Field
    @Cascade(delete = true)
    @Persistent(table = "nms_talukas_join_health_blocks", mappedBy = "talukas", defaultFetchGroup = "true")
    @Join(column = "taluka_id")
    @Element(column = "healthblock_id")
    @JsonManagedReference
    private List<HealthBlock> healthBlocks;
```

That MDS will delete the old one to many join column and create the join table.  We'll then have to add a new import that takes the Taluka HealthBlock mapping file and have it populate the joined fields.  That file will have to be imported after all the other data is imported.  

We'll also have to update the validation code since currently it isn't valid to have  HealthBlock that isn't related to a Taluka.  That check will have to be removed.

**Comment by frankhuster** [comment]
We'll also have to make sure (if we don't already) that it's ok to import
MCTS beneficiaries with location data that doesn't exist in the database.
At MCTS today they explained that they would have new location info daily
and that the new beneficiaries would be tagged with this location data.
So we should be able to import a beneficiary from a Taluka (or possibly any
other location type) that doesn't exist (yet) in our system.

On Wed, Oct 14, 2015 at 9:52 AM, Rob LaRubbio <notifications@github.com>
wrote:

> We need to verify that if we delete
>
>     @Field
>     @Column(allowsNull = "false")
>     @NotNull
>     @JsonBackReference
>     private Taluka taluka;
>
> From HealthBlock.java and replace it with
>
>     @Field
>     @JsonBackReference
>     private List<Taluka> talukas;
>
> and change this in Taluka.java
>
>     @Field
>     @Cascade(delete = true)
>     @Persistent(mappedBy = "taluka", defaultFetchGroup = "true")
>     @JsonManagedReference
>     private List<HealthBlock> healthBlocks;
>
> to
>
>     @Field
>     @Cascade(delete = true)
>     @Persistent(table = "nms_talukas_join_health_blocks", mappedBy = "talukas", defaultFetchGroup = "true")
>     @Join(column = "taluka_id")
>     @Element(column = "healthblock_id")
>     @JsonManagedReference
>     private List<HealthBlock> healthBlocks;
>
> That MDS will delete the old one to many join column and create the join
> table. We'll then have to add a new import that takes the Taluka
> HealthBlock mapping file and have it populate the joined fields. That file
> will have to be imported after all the other data is imported.
>
> We'll also have to update the validation code since currently it isn't
> valid to have HealthBlock that isn't related to a Taluka. That check will
> have to be removed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/595#issuecomment-148114421>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by larubbio** [comment]
I'm not sure about that one.  Currently we will reject them.  We can import
them but not any location level below the not yet imported data, as long as
state and district are correct.  Later that information can be updated if
needed.

That field is a foriegn relationship in the system.  So we would have to
drop that rule and I think that could allow for all sorts of bad data
(since the source isn't really clean)

**Comment by frankhuster** [comment]
Yeah, I was thinking dropping the checks might even make the MCTS import a
bit faster ;-)
So I guess the important question would be what do we do for people who
come in with district IDs we don't know.
Should we run that by BBC?

On Wed, Oct 14, 2015 at 10:16 AM, Rob LaRubbio <notifications@github.com>
wrote:

> I'm not sure about that one. Currently we will reject them. We can import
> them but not any location level below the not yet imported data, as long as
> state and district are correct. Later that information can be updated if
> needed.
>
> That field is a foriegn relationship in the system. So we would have to
> drop that rule and I think that could allow for all sorts of bad data
> (since the source isn't really clean)
>
> On Wed, Oct 14, 2015 at 10:06 AM, Frank Huster <notifications@github.com>
> wrote:
>
>
> > We'll also have to make sure (if we don't already) that it's ok to import
> > MCTS beneficiaries with location data that doesn't exist in the database.
> > At MCTS today they explained that they would have new location info daily
> > and that the new beneficiaries would be tagged with this location data.
> > So we should be able to import a beneficiary from a Taluka (or possibly
> any
> > other location type) that doesn't exist (yet) in our system.
> >
> > On Wed, Oct 14, 2015 at 9:52 AM, Rob LaRubbio <notifications@github.com>
> > wrote:
> >
> > > We need to verify that if we delete
> > >
> > > @Field
> > > @Column(allowsNull = "false")
> > > @NotNull
> > > @JsonBackReference
> > > private Taluka taluka;
> > >
> > > From HealthBlock.java and replace it with
> > >
> > > @Field
> > > @JsonBackReference
> > > private List<Taluka> talukas;
> > >
> > > and change this in Taluka.java
> > >
> > > @Field
> > > @Cascade(delete = true)
> > > @Persistent(mappedBy = "taluka", defaultFetchGroup = "true")
> > > @JsonManagedReference
> > > private List<HealthBlock> healthBlocks;
> > >
> > > to
> > >
> > > @Field
> > > @Cascade(delete = true)
> > > @Persistent(table = "nms_talukas_join_health_blocks", mappedBy =
> > "talukas", defaultFetchGroup = "true")
> > > @Join(column = "taluka_id")
> > > @Element(column = "healthblock_id")
> > > @JsonManagedReference
> > > private List<HealthBlock> healthBlocks;
> > >
> > > That MDS will delete the old one to many join column and create the
> join
> > > table. We'll then have to add a new import that takes the Taluka
> > > HealthBlock mapping file and have it populate the joined fields. That
> > file
> > > will have to be imported after all the other data is imported.
> > >
> > > We'll also have to update the validation code since currently it isn't
> > > valid to have HealthBlock that isn't related to a Taluka. That check
> will
> > > have to be removed.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/motech-implementations/mim/issues/595#issuecomment-148114421
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Frank Huster
> > Mobile Health Innovations
> > Grameen Foundation
> > +1.206.325.6690 x201
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/motech-implementations/mim/issues/595#issuecomment-148119751
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/595#issuecomment-148123057>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by larubbio** [comment]
How often does the location data come from mcts?  How often does the flw
and beneficiary data come in?  Also what changes can come in the location
update?  Just additions?  We don't even handle deletions.  Can one record
move to another parent in the hierarchy?  None of that was spec'd and I'm
not sure what the system behavior will be for those cases.

**Comment by frankhuster** [comment]
Both location & beneficiary data change daily.

Not sure about the master location data numbers, but for the recipients
it's in the thousands daily.
And I'm not sure if the location data attached to 'old' recipients already
in our system can be changed, but I think it can. (Kosh, remember?)
I guess we can live with that and ignore location changes on MCTS
beneficiary updates where the new location doesn't exist?

And yes, a location can suddenly have a new parent...
Dealing with regular master location updates (web services or file import)
is kind of a large amount of work that isn't part of what we're supposed to
do, right?



On Wed, Oct 14, 2015 at 5:28 PM, Rob LaRubbio <notifications@github.com>
wrote:

> How often does the location data come from mcts? How often does the flw
> and beneficiary data come in? Also what changes can come in the location
> update? Just additions? We don't even handle deletions. Can one record
> move to another parent in the hierarchy? None of that was spec'd and I'm
> not sure what the system behavior will be for those cases.
>
> On Wed, Oct 14, 2015 at 5:18 PM, Frank Huster <notifications@github.com>
> wrote:
>
>
> > Yeah, I was thinking dropping the checks might even make the MCTS import
> a
> > bit faster ;-)
> > So I guess the important question would be what do we do for people who
> > come in with district IDs we don't know.
> > Should we run that by BBC?
> >
> > On Wed, Oct 14, 2015 at 10:16 AM, Rob LaRubbio <notifications@github.com
> >
> >
> > wrote:
> >
> > > I'm not sure about that one. Currently we will reject them. We can
> import
> > > them but not any location level below the not yet imported data, as
> long
> > as
> > > state and district are correct. Later that information can be updated
> if
> > > needed.
> > >
> > > That field is a foriegn relationship in the system. So we would have to
> > > drop that rule and I think that could allow for all sorts of bad data
> > > (since the source isn't really clean)
> > >
> > > On Wed, Oct 14, 2015 at 10:06 AM, Frank Huster <
> notifications@github.com
> > >
> > > wrote:
> > >
> > >
> > > > We'll also have to make sure (if we don't already) that it's ok to
> > import
> > > > MCTS beneficiaries with location data that doesn't exist in the
> > database.
> > > > At MCTS today they explained that they would have new location info
> > daily
> > > > and that the new beneficiaries would be tagged with this location
> data.
> > > > So we should be able to import a beneficiary from a Taluka (or
> possibly
> > > any
> > > > other location type) that doesn't exist (yet) in our system.
> > > >
> > > > On Wed, Oct 14, 2015 at 9:52 AM, Rob LaRubbio <
> > notifications@github.com>
> > > > wrote:
> > > >
> > > > > We need to verify that if we delete
> > > > >
> > > > > @Field
> > > > > @Column(allowsNull = "false")
> > > > > @NotNull
> > > > > @JsonBackReference
> > > > > private Taluka taluka;
> > > > >
> > > > > From HealthBlock.java and replace it with
> > > > >
> > > > > @Field
> > > > > @JsonBackReference
> > > > > private List<Taluka> talukas;
> > > > >
> > > > > and change this in Taluka.java
> > > > >
> > > > > @Field
> > > > > @Cascade(delete = true)
> > > > > @Persistent(mappedBy = "taluka", defaultFetchGroup = "true")
> > > > > @JsonManagedReference
> > > > > private List<HealthBlock> healthBlocks;
> > > > >
> > > > > to
> > > > >
> > > > > @Field
> > > > > @Cascade(delete = true)
> > > > > @Persistent(table = "nms_talukas_join_health_blocks", mappedBy =
> > > > "talukas", defaultFetchGroup = "true")
> > > > > @Join(column = "taluka_id")
> > > > > @Element(column = "healthblock_id")
> > > > > @JsonManagedReference
> > > > > private List<HealthBlock> healthBlocks;
> > > > >
> > > > > That MDS will delete the old one to many join column and create the
> > > join
> > > > > table. We'll then have to add a new import that takes the Taluka
> > > > > HealthBlock mapping file and have it populate the joined fields.
> That
> > > > file
> > > > > will have to be imported after all the other data is imported.
> > > > >
> > > > > We'll also have to update the validation code since currently it
> > isn't
> > > > > valid to have HealthBlock that isn't related to a Taluka. That
> check
> > > will
> > > > > have to be removed.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/motech-implementations/mim/issues/595#issuecomment-148114421
> > > > >
> > > > > .
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Frank Huster
> > > > Mobile Health Innovations
> > > > Grameen Foundation
> > > > +1.206.325.6690 x201
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/motech-implementations/mim/issues/595#issuecomment-148119751
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/motech-implementations/mim/issues/595#issuecomment-148123057
> > >
> >
> > > .
> > >
> >
> >
> >
> > --
> > Frank Huster
> > Mobile Health Innovations
> > Grameen Foundation
> > +1.206.325.6690 x201
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/motech-implementations/mim/issues/595#issuecomment-148239048
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/595#issuecomment-148240304>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201
