### ISSUE TITLE
Find an elegant way to generate an internal server error HTTP 500 in and test it in BaseController

### ISSUE THREAD

**Issue by frankhuster** [motech-implementations/mim#60]

**Comment by llavoie** [comment]
Duplicate of #43?

**Comment by larubbio** [comment]
This one is about how to generate a 500 and the other is about adding a test for it.  I guess they are two sides of the same coin.

**Comment by llavoie** [comment]
Oops! 

-----Original Message-----

**Comment by larubbio** [comment]
I closed the other one.

I think the way to do this is in a unit test where we mock out the
controller method and force it to throw

**Comment by larubbio** [comment]
I was thinking of doing this, but I think I'll have to spend a lot of time getting a deeper understanding of spring configuration.

http://www.petrikainulainen.net/programming/spring-framework/unit-testing-of-spring-mvc-controllers-configuration/

@llavoie Do you think we can ask soldevelo for help on this (or @frankhuster how is your spring knowledge?)

**Comment by llavoie** [comment]
@larubbio  I think it makes a lot of sense to ask SolDevelo. Do we want them to do the work for us, or just advise? If the latter, perhaps we just post a question on the mailing list.

**Comment by larubbio** [comment]
Maybe have them do it?  I don' think it is that much work if you know the framework.  They could just get a test that throws and put a blank handler in we can fill it out with the appropriate logic.

We can then move this ticket to Sprint 2

**Comment by llavoie** [comment]
Ok, let's move it to sprint 2. I'll ping Pawel and see if he can nominate someone.

**Comment by larubbio** [comment]
Great.  I've moved it and added the 'help wanted' label just because it exists.
