### ISSUE TITLE
Use shorter table names

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#61]
Currently we are using the default names, but we can provide one in the @Entity annotation, so we should:

http://docs.motechproject.org/en/latest/get_started/model_data/model_data.html
tableName - The actual name of the table in the database for this entity. Allows users to directly control the name in the data store. The default table name will take the form of: MDS_<MODULE>_<NAMESPACE>_<ENTITY_NAME>. If an entity has no namespace or module, those parts will be omitted.

**Comment by frankhuster** [comment]
I assume we want to standardize that over the entire project.
Which naming convention should we use?

**Comment by larubbio** [comment]
I was thinking we'd just use the entity name with underscores.  So
eliminate the MDS_MODULE_ prefix from them.
