### ISSUE TITLE
Interface or Upload mechanism for adding users to the whitelist

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#68]

**Comment by larubbio** [comment]
If the CSV contains the MDS ID for the state then this can be done via the existing MDS CSV upload

Q: Can MDS' CSV upload be used if one of the fields is a related field to another entity?
A: Yes, but only through IDs. If you place an ID(or IDs) in the related field in the CSV file, then MDS will try to create a relationship between the existing object with the given ID and the object being imported. The related objects have to exist before the import though, so importing related objects is limited."

So assuming a CSV format of "state,contactNumber" is used and state is the MDS ID for the state then this is completed.

@llavoie thoughts?

**Comment by llavoie** [comment]
I think this sounds ok. Do we need to manually verify that the import works?

-----Original Message-----

**Comment by larubbio** [comment]
@llavoie Is there an FT for that?  If so I think we can close this and let that verify for us.

**Comment by llavoie** [comment]
Presumably, but I don't remember offhand. We'd need to check the test plan.

On Wed, Jun 24, 2015 at 2:59 PM, Rob LaRubbio <notifications@github.com>
wrote:

> @llavoie <https://github.com/llavoie> Is there an FT for that? If so I
> think we can close this and let that verify for us.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/issues/68#issuecomment-115023788>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by larubbio** [comment]
Current FT is for kilkari only and it doesn't have whitelist.  The FT plan for MA/MK should be coming in soon and we can verify that this is in it.
