### ISSUE TITLE
When the spec says a string field is mandatory, should that field be at least one char long?

### ISSUE THREAD

**Issue by frankhuster** [motech-implementations/mim#91]
Or do we accept empty strings a valid mandatory string fields?

**Comment by larubbio** [comment]
What section of the spec?

**Comment by frankhuster** [comment]
In the PDF, all APIs have a table containing a "Mandatory" column.
For example see 2.2.6.1.6 mentions operator as a mandatory string of 255
characters max, but specifies no minimum.



On Fri, Apr 24, 2015 at 3:58 PM, Rob LaRubbio <notifications@github.com>
wrote:

> What section of the spec?
>
> On Fri, Apr 24, 2015 at 3:58 PM, Frank Huster <notifications@github.com>
> wrote:
>
> > Or do we accept empty strings a valid mandatory string fields?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/koshalt/mim/issues/91>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koshalt/mim/issues/91#issuecomment-96090505>.
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by larubbio** [comment]
In the word doc that column is:

Man
dato
ry

:)

**Comment by larubbio** [comment]
I don't see why those are max 255 when tables 5.4 and 5.3 define circle
code as 2 characters and operator as 1.

I would define mandatory here as not null and length > 0

**Comment by llavoie** [comment]
+1 for Rob's definition.

On Fri, Apr 24, 2015 at 4:27 PM, Rob LaRubbio <notifications@github.com>
wrote:

> I don't see why those are max 255 when tables 5.4 and 5.3 define circle
> code as 2 characters and operator as 1.
>
> I would define mandatory here as not null and length > 0
>
>
> On Fri, Apr 24, 2015 at 4:21 PM, Frank Huster <notifications@github.com>
> wrote:
>
> > In the PDF, all APIs have a table containing a "Mandatory" column.
> > For example see 2.2.6.1.6 mentions operator as a mandatory string of 255
> > characters max, but specifies no minimum.
> >
> >
> >
> > On Fri, Apr 24, 2015 at 3:58 PM, Rob LaRubbio <notifications@github.com>
> > wrote:
> >
> > > What section of the spec?
> > >
> > > On Fri, Apr 24, 2015 at 3:58 PM, Frank Huster <
> notifications@github.com>
> > > wrote:
> > >
> > > > Or do we accept empty strings a valid mandatory string fields?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/koshalt/mim/issues/91>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/koshalt/mim/issues/91#issuecomment-96090505>.
> > >
> >
> >
> >
> > --
> > Frank Huster
> > Mobile Health Innovations
> > Grameen Foundation
> > +1.206.325.6690 x201
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/koshalt/mim/issues/91#issuecomment-96095202>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koshalt/mim/issues/91#issuecomment-96099259>.
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by llavoie** [comment]
We could use apache commons-lang or google guava to get an equivalent method to C#'s string.isNullOrEmpty  (which also checks for blank strings)

**Comment by koshalt** [comment]
+1.

I agree. This is one of the things that I was pushing for with Aricent to
use existing libraries than reimplement all the functions.

**Comment by frankhuster** [comment]
We already use ```StringUtils.isBlank()``` in the modules & platform code.

**Comment by frankhuster** [comment]
Oops, never mind ```StringUtils.isBlank()``` returns true if the string has whitespace.
We want ```StringUtils.isNotEmpty()```.
But that's what ```BaseController.validateFieldString()``` does, and it also sets the ```failureReason```.

**Comment by larubbio** [comment]
What does that return for this string:

new String("blank");

**Comment by frankhuster** [comment]
:smiling_imp:

**Comment by koshalt** [comment]
I think it goes into inception at that point..

http://www.reactiongifs.com/r/drj1NmK.gif

**Comment by larubbio** [comment]
Did you really reference Inception with a reaction gif from The Great Gatsby?

![facepalm](http://www.reactiongifs.com/wp-content/uploads/2012/11/naked-gun-facepalm.gif)

**Comment by koshalt** [comment]
http://www.reactiongifs.com/r/knee.gif

**Comment by frankhuster** [comment]
We all agree that a valid string is not null and length() > 0
