### ISSUE TITLE
NMS.GEN.LOC.001 - Import of location data

### ISSUE THREAD

**Issue by larubbio** [motech-implementations/mim#97]
The NMS system shall provide means to upload location data in CSV file (or from web service) into its internal database via a web interface.
Multiple upload attempts shall be supported whereby the complete location data may not be available in the beginning.
Errors during location data upload shall be logged.

**Comment by llavoie** [comment]
@larubbio please add schema info

**Comment by larubbio** [comment]
![screen shot 2015-05-13 at 11 56 44 am](https://cloud.githubusercontent.com/assets/51527/7618483/443becba-f967-11e4-9da6-b52e0c217bad.png)

![screen shot 2015-05-13 at 11 56 50 am](https://cloud.githubusercontent.com/assets/51527/7618498/4ff240e0-f967-11e4-8211-ec808330e995.png)

![screen shot 2015-05-13 at 11 57 14 am](https://cloud.githubusercontent.com/assets/51527/7618504/589487bc-f967-11e4-837a-05d37d087f35.png)

![screen shot 2015-05-13 at 11 56 55 am](https://cloud.githubusercontent.com/assets/51527/7618511/5ee6420e-f967-11e4-9845-893a946c8bb0.png)

![screen shot 2015-05-13 at 11 57 01 am](https://cloud.githubusercontent.com/assets/51527/7618517/65bc47ae-f967-11e4-8ec5-ec2a509685b6.png)

![screen shot 2015-05-13 at 11 57 07 am](https://cloud.githubusercontent.com/assets/51527/7618520/695ede26-f967-11e4-854b-19f540f1bda1.png)
